# Generated by Django 4.2.29 on 2026-03-12 10:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('geography', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='School',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('legacy_id', models.IntegerField(blank=True, null=True, unique=True)),
                ('uid', models.CharField(blank=True, default='', max_length=64)),
                ('code', models.CharField(max_length=64, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('district_name', models.CharField(blank=True, max_length=120)),
                ('sub_county_name', models.CharField(blank=True, max_length=120)),
                ('parish_name', models.CharField(blank=True, max_length=120)),
                ('village', models.CharField(blank=True, max_length=120)),
                ('gps_lat', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('gps_lng', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('enrollment_total', models.PositiveIntegerField(default=0)),
                ('enrolled_boys', models.PositiveIntegerField(default=0)),
                ('enrolled_girls', models.PositiveIntegerField(default=0)),
                ('program_status', models.CharField(choices=[('active', 'Active'), ('graduated', 'Graduated'), ('paused', 'Paused'), ('monitoring', 'Monitoring')], default='active', max_length=24)),
                ('graduated_at', models.DateTimeField(blank=True, null=True)),
                ('graduation_notes', models.TextField(blank=True)),
                ('district', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='schools', to='geography.district')),
                ('parish', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='schools', to='geography.parish')),
                ('region', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='schools', to='geography.region')),
                ('subcounty', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='schools', to='geography.subcounty')),
                ('subregion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='schools', to='geography.subregion')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('legacy_id', models.IntegerField(blank=True, null=True, unique=True)),
                ('uid', models.CharField(max_length=64, unique=True)),
                ('full_name', models.CharField(max_length=255)),
                ('gender', models.CharField(choices=[('male', 'Male'), ('female', 'Female'), ('other', 'Other')], max_length=16)),
                ('is_reading_teacher', models.BooleanField(default=True)),
                ('phone', models.CharField(blank=True, max_length=40)),
                ('status', models.CharField(default='active', max_length=32)),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teachers', to='schools.school')),
            ],
            options={
                'ordering': ['school_id', 'full_name'],
            },
        ),
        migrations.CreateModel(
            name='SchoolGraduationWorkflow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('state', models.CharField(choices=[('pending', 'Pending'), ('kept_supporting', 'Kept Supporting'), ('needs_review', 'Needs Review'), ('graduated', 'Graduated'), ('monitoring', 'Monitoring')], default='pending', max_length=32)),
                ('snoozed_until', models.DateField(blank=True, null=True)),
                ('reason', models.TextField(blank=True)),
                ('checklist_answers', models.JSONField(blank=True, default=dict)),
                ('assigned_supervisor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='graduation_assignments', to=settings.AUTH_USER_MODEL)),
                ('school', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='graduation_workflow', to='schools.school')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SchoolContact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('legacy_id', models.IntegerField(blank=True, null=True, unique=True)),
                ('uid', models.CharField(blank=True, default='', max_length=64)),
                ('full_name', models.CharField(max_length=255)),
                ('gender', models.CharField(choices=[('male', 'Male'), ('female', 'Female'), ('other', 'Other')], max_length=16)),
                ('category', models.CharField(choices=[('proprietor', 'Proprietor'), ('head_teacher', 'Head Teacher'), ('deputy_head', 'Deputy Head Teacher'), ('dos', 'Director of Studies'), ('teacher', 'Teacher'), ('administrator', 'Administrator'), ('accountant', 'Accountant')], max_length=32)),
                ('role_title', models.CharField(blank=True, max_length=120)),
                ('phone', models.CharField(blank=True, max_length=40)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('whatsapp', models.CharField(blank=True, max_length=40)),
                ('class_taught', models.CharField(blank=True, max_length=64)),
                ('subject_taught', models.CharField(blank=True, max_length=64)),
                ('is_primary_contact', models.BooleanField(default=False)),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contacts', to='schools.school')),
            ],
            options={
                'ordering': ['school_id', 'full_name'],
            },
        ),
        migrations.AddConstraint(
            model_name='schoolcontact',
            constraint=models.UniqueConstraint(condition=models.Q(('is_primary_contact', True)), fields=('school',), name='unique_primary_contact_per_school'),
        ),
    ]
