# Generated by Django 4.2.29 on 2026-03-12 10:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('schools', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BlogPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('legacy_id', models.IntegerField(blank=True, null=True, unique=True)),
                ('slug', models.SlugField(max_length=200, unique=True)),
                ('title', models.CharField(max_length=255)),
                ('summary', models.TextField(blank=True)),
                ('content_markdown', models.TextField(blank=True)),
                ('category', models.CharField(blank=True, max_length=120)),
                ('cover_image_url', models.URLField(blank=True)),
                ('publish_status', models.CharField(default='draft', max_length=24)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('author_name', models.CharField(blank=True, max_length=120)),
            ],
            options={
                'ordering': ['-published_at', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='NewsletterIssue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('legacy_id', models.IntegerField(blank=True, null=True, unique=True)),
                ('slug', models.SlugField(max_length=200, unique=True)),
                ('title', models.CharField(max_length=255)),
                ('summary', models.TextField(blank=True)),
                ('html_content', models.TextField(blank=True)),
                ('status', models.CharField(default='draft', max_length=24)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-published_at', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Resource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('legacy_id', models.IntegerField(blank=True, null=True, unique=True)),
                ('title', models.CharField(max_length=255)),
                ('slug', models.SlugField(max_length=200, unique=True)),
                ('description', models.TextField(blank=True)),
                ('external_url', models.URLField(blank=True)),
                ('is_published', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['title'],
            },
        ),
        migrations.CreateModel(
            name='StoryAnthology',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('legacy_id', models.IntegerField(blank=True, null=True, unique=True)),
                ('slug', models.SlugField(max_length=160, unique=True)),
                ('title', models.CharField(max_length=255)),
                ('edition', models.CharField(blank=True, max_length=64)),
                ('publish_status', models.CharField(default='draft', max_length=24)),
                ('consent_status', models.CharField(default='pending', max_length=24)),
                ('featured', models.BooleanField(default=False)),
                ('featured_rank', models.IntegerField(blank=True, null=True)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('school', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='anthologies', to='schools.school')),
            ],
            options={
                'ordering': ['-featured', 'featured_rank', '-published_at', 'title'],
            },
        ),
        migrations.CreateModel(
            name='Story',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('legacy_id', models.IntegerField(blank=True, null=True, unique=True)),
                ('slug', models.SlugField(max_length=200, unique=True)),
                ('title', models.CharField(max_length=255)),
                ('excerpt', models.TextField(blank=True)),
                ('content_text', models.TextField(blank=True)),
                ('grade', models.CharField(blank=True, max_length=32)),
                ('language', models.CharField(default='English', max_length=64)),
                ('tags', models.JSONField(blank=True, default=list)),
                ('publish_status', models.CharField(default='draft', max_length=24)),
                ('consent_status', models.CharField(default='pending', max_length=24)),
                ('public_author_display', models.CharField(blank=True, max_length=255)),
                ('view_count', models.PositiveIntegerField(default=0)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('anthology', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stories', to='content.storyanthology')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stories', to='schools.school')),
            ],
            options={
                'ordering': ['-published_at', '-created_at'],
            },
        ),
    ]
