DO $$
BEGIN
  IF EXISTS (
    SELECT 1
    FROM information_schema.columns
    WHERE table_name = 'portal_users'
      AND column_name = 'id'
      AND is_identity = 'NO'
  ) THEN
    ALTER TABLE portal_users
      ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY;
  END IF;
EXCEPTION
  WHEN duplicate_object THEN
    NULL;
END $$;

CREATE TABLE IF NOT EXISTS teaching_improvement_settings (
  id INTEGER PRIMARY KEY,
  teacher_delta_threshold DOUBLE PRECISION NOT NULL DEFAULT 0.3,
  min_domains_improved INTEGER NOT NULL DEFAULT 2,
  school_delta_threshold DOUBLE PRECISION NOT NULL DEFAULT 0.2,
  school_improved_teachers_percent_threshold DOUBLE PRECISION NOT NULL DEFAULT 50,
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  CHECK (id = 1)
);

CREATE TABLE IF NOT EXISTS portal_training_attendance (
  id INTEGER PRIMARY KEY,
  portal_record_id INTEGER NOT NULL REFERENCES portal_records(id) ON DELETE CASCADE,
  school_id INTEGER REFERENCES schools_directory(id) ON DELETE SET NULL,
  participant_name TEXT NOT NULL,
  participant_role TEXT NOT NULL,
  gender TEXT,
  teacher_uid TEXT,
  phone TEXT,
  email TEXT,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  contact_id INTEGER,
  contact_uid TEXT,
  role_at_time TEXT,
  attended BOOLEAN NOT NULL DEFAULT TRUE
);
CREATE INDEX IF NOT EXISTS idx_portal_training_attendance_record
  ON portal_training_attendance(portal_record_id);
CREATE INDEX IF NOT EXISTS idx_portal_training_attendance_teacher
  ON portal_training_attendance(teacher_uid);
CREATE INDEX IF NOT EXISTS idx_portal_training_attendance_school
  ON portal_training_attendance(school_id);

CREATE TABLE IF NOT EXISTS lesson_evaluations (
  id INTEGER PRIMARY KEY,
  school_id INTEGER NOT NULL REFERENCES schools_directory(id) ON DELETE CASCADE,
  teacher_uid TEXT NOT NULL REFERENCES teacher_roster(teacher_uid) ON DELETE CASCADE,
  grade TEXT NOT NULL CHECK(grade IN ('P1','P2','P3','P4','P5','P6','P7')),
  stream TEXT,
  class_size INTEGER,
  lesson_date DATE NOT NULL,
  lesson_focus_json TEXT NOT NULL DEFAULT '[]',
  observer_id INTEGER NOT NULL REFERENCES portal_users(id),
  visit_id INTEGER,
  overall_score DOUBLE PRECISION NOT NULL DEFAULT 0,
  overall_level TEXT NOT NULL DEFAULT 'Needs Support',
  domain_scores_json TEXT NOT NULL DEFAULT '{}',
  top_gap_domain TEXT,
  top_strength_domain TEXT,
  strengths_text TEXT NOT NULL,
  priority_gap_text TEXT NOT NULL,
  next_coaching_action TEXT NOT NULL,
  teacher_commitment TEXT NOT NULL,
  catchup_estimate_count INTEGER,
  catchup_estimate_percent DOUBLE PRECISION,
  next_visit_date DATE,
  status TEXT NOT NULL DEFAULT 'active' CHECK(status IN ('active', 'void')),
  void_reason TEXT,
  voided_by_user_id INTEGER REFERENCES portal_users(id),
  voided_at TIMESTAMPTZ,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);
CREATE INDEX IF NOT EXISTS idx_lesson_evaluations_school_date
  ON lesson_evaluations(school_id, lesson_date DESC);
CREATE INDEX IF NOT EXISTS idx_lesson_evaluations_teacher
  ON lesson_evaluations(teacher_uid, lesson_date DESC);
CREATE INDEX IF NOT EXISTS idx_lesson_evaluations_visit
  ON lesson_evaluations(visit_id);
CREATE INDEX IF NOT EXISTS idx_lesson_evaluations_status
  ON lesson_evaluations(status, lesson_date DESC);

CREATE TABLE IF NOT EXISTS lesson_evaluation_items (
  id INTEGER PRIMARY KEY,
  evaluation_id INTEGER NOT NULL REFERENCES lesson_evaluations(id) ON DELETE CASCADE,
  domain_key TEXT NOT NULL CHECK(domain_key IN ('setup','new_sound','decoding','reading_practice','tricky_words','check_next')),
  item_key TEXT NOT NULL CHECK(item_key IN ('A1','A2','A3','B4','B5','B6','B7','B8','C9','C10','C11','C12','D13','D14','D15','D16','E17','E18','F19','F20','F21')),
  score INTEGER NOT NULL CHECK(score >= 1 AND score <= 4),
  note TEXT,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  UNIQUE(evaluation_id, item_key)
);
CREATE INDEX IF NOT EXISTS idx_lesson_evaluation_items_eval
  ON lesson_evaluation_items(evaluation_id);
CREATE INDEX IF NOT EXISTS idx_lesson_evaluation_items_domain
  ON lesson_evaluation_items(domain_key);

CREATE TABLE IF NOT EXISTS story_activities (
  id INTEGER PRIMARY KEY,
  school_id INTEGER NOT NULL REFERENCES schools_directory(id) ON DELETE CASCADE,
  date DATE NOT NULL,
  session_type TEXT NOT NULL,
  learners_count INTEGER NOT NULL DEFAULT 0,
  drafts_count INTEGER NOT NULL DEFAULT 0,
  revisions_count INTEGER NOT NULL DEFAULT 0,
  notes TEXT,
  created_by_user_id INTEGER NOT NULL REFERENCES portal_users(id),
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  portal_record_id INTEGER UNIQUE
);
CREATE UNIQUE INDEX IF NOT EXISTS idx_story_activities_record
  ON story_activities(portal_record_id);
CREATE INDEX IF NOT EXISTS idx_story_activities_school
  ON story_activities(school_id);
CREATE INDEX IF NOT EXISTS idx_story_activities_date
  ON story_activities(date);

CREATE TABLE IF NOT EXISTS story_anthologies (
  id INTEGER PRIMARY KEY,
  title TEXT NOT NULL,
  school_id INTEGER REFERENCES schools_directory(id) ON DELETE SET NULL,
  district_scope TEXT,
  edition TEXT NOT NULL DEFAULT '',
  pdf_stored_path TEXT,
  cover_image_path TEXT,
  publish_status TEXT NOT NULL DEFAULT 'draft' CHECK(publish_status IN ('draft', 'published')),
  download_count INTEGER NOT NULL DEFAULT 0,
  created_by_user_id INTEGER NOT NULL REFERENCES portal_users(id),
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  slug TEXT NOT NULL DEFAULT '',
  scope_type TEXT NOT NULL DEFAULT 'school',
  scope_id INTEGER,
  pdf_page_count INTEGER NOT NULL DEFAULT 0,
  consent_status TEXT NOT NULL DEFAULT 'pending' CHECK(consent_status IN ('pending', 'approved', 'denied')),
  featured BOOLEAN NOT NULL DEFAULT FALSE,
  featured_rank INTEGER,
  published_at TIMESTAMPTZ
);
CREATE INDEX IF NOT EXISTS idx_story_anth_featured
  ON story_anthologies(featured, featured_rank);

CREATE TABLE IF NOT EXISTS story_library (
  id INTEGER PRIMARY KEY,
  slug TEXT NOT NULL UNIQUE,
  school_id INTEGER NOT NULL REFERENCES schools_directory(id) ON DELETE CASCADE,
  anthology_id INTEGER REFERENCES story_anthologies(id) ON DELETE SET NULL,
  title TEXT NOT NULL,
  author_about TEXT NOT NULL DEFAULT '',
  excerpt TEXT NOT NULL DEFAULT '',
  content_text TEXT,
  pdf_stored_path TEXT,
  cover_image_path TEXT,
  grade TEXT NOT NULL DEFAULT '',
  language TEXT NOT NULL DEFAULT 'English',
  tags TEXT NOT NULL DEFAULT '[]',
  publish_status TEXT NOT NULL DEFAULT 'draft' CHECK(publish_status IN ('draft', 'review', 'published')),
  consent_status TEXT NOT NULL DEFAULT 'pending' CHECK(consent_status IN ('pending', 'approved', 'denied')),
  public_author_display TEXT NOT NULL DEFAULT '',
  learner_uid TEXT,
  view_count INTEGER NOT NULL DEFAULT 0,
  created_by_user_id INTEGER NOT NULL REFERENCES portal_users(id),
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  published_at TIMESTAMPTZ,
  page_start INTEGER NOT NULL DEFAULT 1,
  page_end INTEGER NOT NULL DEFAULT 1,
  sort_order INTEGER NOT NULL DEFAULT 0,
  story_content_blocks TEXT NOT NULL DEFAULT '[]',
  has_illustrations BOOLEAN NOT NULL DEFAULT FALSE,
  author_profile_id INTEGER,
  consent_record_id INTEGER
);
CREATE INDEX IF NOT EXISTS idx_story_library_slug
  ON story_library(slug);
CREATE INDEX IF NOT EXISTS idx_story_library_school
  ON story_library(school_id);
CREATE INDEX IF NOT EXISTS idx_story_library_published
  ON story_library(publish_status, consent_status);
CREATE INDEX IF NOT EXISTS idx_story_library_published_at
  ON story_library(published_at DESC);

CREATE TABLE IF NOT EXISTS observation_rubrics (
  id INTEGER PRIMARY KEY,
  school_id INTEGER NOT NULL REFERENCES schools_directory(id) ON DELETE CASCADE,
  teacher_uid TEXT NOT NULL REFERENCES teacher_roster(teacher_uid) ON DELETE CASCADE,
  date DATE NOT NULL,
  lesson_type TEXT NOT NULL,
  indicators_json TEXT NOT NULL DEFAULT '[]',
  overall_score DOUBLE PRECISION NOT NULL DEFAULT 0,
  strengths TEXT,
  gaps TEXT,
  coaching_actions TEXT,
  created_by_user_id INTEGER NOT NULL REFERENCES portal_users(id),
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);
CREATE INDEX IF NOT EXISTS idx_observation_rubrics_school
  ON observation_rubrics(school_id, date DESC);
CREATE INDEX IF NOT EXISTS idx_observation_rubrics_teacher
  ON observation_rubrics(teacher_uid);

CREATE OR REPLACE VIEW impact_public_school_scope AS
SELECT
  id AS school_id,
  school_uid,
  school_code,
  name AS school_name,
  district,
  COALESCE(sub_region, '') AS sub_region,
  COALESCE(region, '') AS region,
  COALESCE(district_id, '') AS district_id,
  COALESCE(subregion_id, '') AS subregion_id,
  COALESCE(region_id, '') AS region_id,
  CASE
    WHEN COALESCE(enrollment_total, 0) > 0 THEN COALESCE(enrollment_total, 0)
    WHEN COALESCE(enrolled_boys, 0) + COALESCE(enrolled_girls, 0) > 0
      THEN COALESCE(enrolled_boys, 0) + COALESCE(enrolled_girls, 0)
    ELSE COALESCE(enrolled_learners, 0)
  END AS enrollment_total,
  (
    COALESCE(enrolled_baby, 0) +
    COALESCE(enrolled_middle, 0) +
    COALESCE(enrolled_top, 0) +
    COALESCE(enrolled_p1, 0) +
    COALESCE(enrolled_p2, 0) +
    COALESCE(enrolled_p3, 0)
  ) AS direct_impact_total
FROM schools_directory;

CREATE OR REPLACE VIEW impact_public_teacher_support AS
SELECT DISTINCT
  tr.teacher_uid,
  tr.school_id,
  tr.gender
FROM teacher_roster tr
WHERE tr.teacher_uid IN (
  SELECT DISTINCT teacher_uid
  FROM training_participants
  WHERE teacher_uid IS NOT NULL AND btrim(teacher_uid) != ''
)
OR tr.teacher_uid IN (
  SELECT DISTINCT teacher_uid
  FROM portal_training_attendance
  WHERE teacher_uid IS NOT NULL AND btrim(teacher_uid) != ''
)
OR tr.teacher_uid IN (
  SELECT DISTINCT teacher_uid
  FROM observation_rubrics
  WHERE teacher_uid IS NOT NULL AND btrim(teacher_uid) != ''
)
OR tr.teacher_uid IN (
  SELECT DISTINCT teacher_uid
  FROM lesson_evaluations
  WHERE status = 'active'
    AND teacher_uid IS NOT NULL
    AND btrim(teacher_uid) != ''
);

CREATE OR REPLACE VIEW teaching_quality_by_school_period AS
SELECT
  le.school_id,
  to_char(le.lesson_date, 'YYYY-MM') AS period_month,
  COUNT(*) AS evaluations_count,
  AVG(le.overall_score) AS average_overall_score,
  SUM(CASE WHEN le.overall_level = 'Strong' THEN 1 ELSE 0 END) AS strong_count,
  SUM(CASE WHEN le.overall_level = 'Good' THEN 1 ELSE 0 END) AS good_count,
  SUM(CASE WHEN le.overall_level = 'Developing' THEN 1 ELSE 0 END) AS developing_count,
  SUM(CASE WHEN le.overall_level = 'Needs Support' THEN 1 ELSE 0 END) AS needs_support_count
FROM lesson_evaluations le
WHERE le.status = 'active'
GROUP BY le.school_id, to_char(le.lesson_date, 'YYYY-MM');

CREATE OR REPLACE VIEW story_participation_by_school_period AS
WITH
  story_sessions AS (
    SELECT
      sa.school_id,
      to_char(sa.date, 'YYYY-MM') AS period_month,
      COUNT(*) AS sessions_count
    FROM story_activities sa
    GROUP BY sa.school_id, to_char(sa.date, 'YYYY-MM')
  ),
  published_stories AS (
    SELECT
      sl.school_id,
      to_char(COALESCE(sl.published_at, sl.created_at), 'YYYY-MM') AS period_month,
      COUNT(*) AS stories_published
    FROM story_library sl
    WHERE sl.publish_status = 'published'
    GROUP BY sl.school_id, to_char(COALESCE(sl.published_at, sl.created_at), 'YYYY-MM')
  ),
  published_anthologies AS (
    SELECT
      sa.school_id,
      to_char(COALESCE(sa.published_at, sa.created_at), 'YYYY-MM') AS period_month,
      COUNT(*) AS anthologies_published
    FROM story_anthologies sa
    WHERE sa.publish_status = 'published'
      AND sa.school_id IS NOT NULL
    GROUP BY sa.school_id, to_char(COALESCE(sa.published_at, sa.created_at), 'YYYY-MM')
  ),
  periods AS (
    SELECT school_id, period_month FROM story_sessions
    UNION
    SELECT school_id, period_month FROM published_stories
    UNION
    SELECT school_id, period_month FROM published_anthologies
  )
SELECT
  p.school_id,
  p.period_month,
  COALESCE(ss.sessions_count, 0) AS sessions_count,
  COALESCE(ps.stories_published, 0) AS stories_published,
  COALESCE(pa.anthologies_published, 0) AS anthologies_published,
  CASE
    WHEN COALESCE(ss.sessions_count, 0) > 0
      OR COALESCE(ps.stories_published, 0) > 0
      OR COALESCE(pa.anthologies_published, 0) > 0
    THEN 1
    ELSE 0
  END AS active_flag
FROM periods p
LEFT JOIN story_sessions ss
  ON ss.school_id = p.school_id
 AND ss.period_month = p.period_month
LEFT JOIN published_stories ps
  ON ps.school_id = p.school_id
 AND ps.period_month = p.period_month
LEFT JOIN published_anthologies pa
  ON pa.school_id = p.school_id
 AND pa.period_month = p.period_month;

CREATE OR REPLACE VIEW teaching_learning_alignment_by_school_period AS
WITH
  assessment_by_period AS (
    SELECT
      ar.school_id,
      to_char(ar.assessment_date, 'YYYY-MM') AS period_month,
      COUNT(*) AS sample_size,
      AVG(ar.decodable_words_score) AS decoding_avg,
      AVG(ar.story_reading_score) AS fluency_avg,
      AVG(ar.reading_comprehension_score) AS comprehension_avg,
      CASE
        WHEN COUNT(ar.story_reading_score) > 0
        THEN SUM(CASE WHEN ar.story_reading_score < 20 THEN 1 ELSE 0 END) * 100.0 / COUNT(ar.story_reading_score)
        ELSE NULL
      END AS non_reader_pct,
      CASE
        WHEN COUNT(ar.story_reading_score) > 0
        THEN SUM(CASE WHEN ar.story_reading_score >= 20 THEN 1 ELSE 0 END) * 100.0 / COUNT(ar.story_reading_score)
        ELSE NULL
      END AS cwpm20_plus_pct
    FROM assessment_records ar
    GROUP BY ar.school_id, to_char(ar.assessment_date, 'YYYY-MM')
  ),
  periods AS (
    SELECT school_id, period_month FROM teaching_quality_by_school_period
    UNION
    SELECT school_id, period_month FROM assessment_by_period
    UNION
    SELECT school_id, period_month FROM story_participation_by_school_period
  )
SELECT
  p.school_id,
  p.period_month,
  tq.evaluations_count AS teaching_evaluations_count,
  tq.average_overall_score AS teaching_quality_avg,
  abp.sample_size AS learner_sample_size,
  abp.decoding_avg,
  abp.fluency_avg,
  abp.comprehension_avg,
  abp.non_reader_pct,
  abp.cwpm20_plus_pct,
  COALESCE(sp.sessions_count, 0) AS story_sessions_count,
  COALESCE(sp.stories_published, 0) AS stories_published_count,
  COALESCE(sp.anthologies_published, 0) AS anthologies_published_count,
  COALESCE(sp.active_flag, 0) AS story_active_flag
FROM periods p
LEFT JOIN teaching_quality_by_school_period tq
  ON tq.school_id = p.school_id
 AND tq.period_month = p.period_month
LEFT JOIN assessment_by_period abp
  ON abp.school_id = p.school_id
 AND abp.period_month = p.period_month
LEFT JOIN story_participation_by_school_period sp
  ON sp.school_id = p.school_id
 AND sp.period_month = p.period_month;
