CREATE TABLE IF NOT EXISTS finance_contacts (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name TEXT NOT NULL,
  emails_json TEXT NOT NULL DEFAULT '[]',
  phone TEXT,
  whatsapp TEXT,
  address TEXT,
  contact_type TEXT NOT NULL CHECK(contact_type IN ('donor', 'partner', 'sponsor', 'other')),
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS finance_files (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  source_type TEXT NOT NULL,
  source_id INTEGER NOT NULL,
  file_name TEXT NOT NULL,
  stored_path TEXT NOT NULL,
  mime_type TEXT NOT NULL,
  size_bytes INTEGER NOT NULL,
  uploaded_by_user_id INTEGER NOT NULL REFERENCES portal_users(id),
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);
CREATE INDEX IF NOT EXISTS idx_finance_files_source ON finance_files(source_type, source_id);

CREATE TABLE IF NOT EXISTS finance_settings (
  id INTEGER PRIMARY KEY,
  from_email TEXT,
  cc_finance_email TEXT,
  invoice_prefix TEXT NOT NULL DEFAULT 'INV',
  receipt_prefix TEXT NOT NULL DEFAULT 'RCT',
  expense_prefix TEXT NOT NULL DEFAULT 'EXP',
  subcategories_json TEXT NOT NULL DEFAULT '{}',
  invoice_email_template TEXT NOT NULL,
  receipt_email_template TEXT NOT NULL,
  payment_instructions TEXT NOT NULL DEFAULT '',
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  cash_threshold_ugx DOUBLE PRECISION NOT NULL DEFAULT 2000000,
  cash_threshold_usd DOUBLE PRECISION NOT NULL DEFAULT 500,
  backdate_days_limit INTEGER NOT NULL DEFAULT 30,
  allow_receipt_mismatch_override INTEGER NOT NULL DEFAULT 1,
  allow_receipt_reuse_override INTEGER NOT NULL DEFAULT 0,
  outlier_multiplier DOUBLE PRECISION NOT NULL DEFAULT 3,
  CHECK (id = 1)
);

CREATE TABLE IF NOT EXISTS finance_invoices (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  invoice_number TEXT NOT NULL UNIQUE,
  contact_id INTEGER NOT NULL REFERENCES finance_contacts(id),
  category TEXT NOT NULL CHECK(category IN ('Donations', 'Contracts', 'Sponsorship')),
  display_category TEXT,
  issue_date DATE NOT NULL,
  due_date DATE NOT NULL,
  currency TEXT NOT NULL DEFAULT 'UGX',
  subtotal DOUBLE PRECISION NOT NULL DEFAULT 0,
  tax DOUBLE PRECISION NOT NULL DEFAULT 0,
  total DOUBLE PRECISION NOT NULL DEFAULT 0,
  paid_amount DOUBLE PRECISION NOT NULL DEFAULT 0,
  balance_due DOUBLE PRECISION NOT NULL DEFAULT 0,
  status TEXT NOT NULL CHECK(status IN ('draft', 'sent', 'partially_paid', 'paid', 'overdue', 'void')) DEFAULT 'draft',
  notes TEXT,
  pdf_stored_path TEXT,
  pdf_file_id INTEGER,
  emailed_at TIMESTAMPTZ,
  last_sent_to TEXT,
  void_reason TEXT,
  created_by_user_id INTEGER NOT NULL REFERENCES portal_users(id),
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);
CREATE INDEX IF NOT EXISTS idx_finance_invoices_status ON finance_invoices(status);
CREATE INDEX IF NOT EXISTS idx_finance_invoices_due_date ON finance_invoices(due_date);
CREATE INDEX IF NOT EXISTS idx_finance_invoices_contact ON finance_invoices(contact_id);

CREATE TABLE IF NOT EXISTS finance_invoice_items (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  invoice_id INTEGER NOT NULL REFERENCES finance_invoices(id) ON DELETE CASCADE,
  description TEXT NOT NULL,
  qty DOUBLE PRECISION NOT NULL DEFAULT 1,
  unit_price DOUBLE PRECISION NOT NULL DEFAULT 0,
  amount DOUBLE PRECISION NOT NULL DEFAULT 0,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);
CREATE INDEX IF NOT EXISTS idx_finance_invoice_items_invoice ON finance_invoice_items(invoice_id);

CREATE TABLE IF NOT EXISTS finance_receipts (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  receipt_number TEXT NOT NULL UNIQUE,
  contact_id INTEGER NOT NULL REFERENCES finance_contacts(id),
  category TEXT NOT NULL CHECK(category IN ('Donations', 'Contracts', 'Sponsorship')),
  display_category TEXT,
  received_from TEXT NOT NULL,
  receipt_date DATE NOT NULL,
  currency TEXT NOT NULL DEFAULT 'UGX',
  amount_received DOUBLE PRECISION NOT NULL DEFAULT 0,
  payment_method TEXT NOT NULL CHECK(payment_method IN ('cash', 'bank_transfer', 'mobile_money', 'cheque', 'other')),
  reference_no TEXT,
  related_invoice_id INTEGER REFERENCES finance_invoices(id) ON DELETE SET NULL,
  description TEXT,
  notes TEXT,
  status TEXT NOT NULL CHECK(status IN ('draft', 'issued', 'void')) DEFAULT 'draft',
  pdf_stored_path TEXT,
  pdf_file_id INTEGER,
  emailed_at TIMESTAMPTZ,
  last_sent_to TEXT,
  void_reason TEXT,
  created_by_user_id INTEGER NOT NULL REFERENCES portal_users(id),
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  restricted_flag INTEGER DEFAULT 0,
  restricted_program TEXT,
  restricted_geo_scope TEXT,
  restricted_geo_id INTEGER,
  restriction_notes TEXT
);
CREATE INDEX IF NOT EXISTS idx_finance_receipts_status ON finance_receipts(status);
CREATE INDEX IF NOT EXISTS idx_finance_receipts_date ON finance_receipts(receipt_date);
CREATE INDEX IF NOT EXISTS idx_finance_receipts_invoice ON finance_receipts(related_invoice_id);

CREATE TABLE IF NOT EXISTS finance_payments (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  related_invoice_id INTEGER NOT NULL REFERENCES finance_invoices(id),
  date DATE NOT NULL,
  amount DOUBLE PRECISION NOT NULL DEFAULT 0,
  currency TEXT NOT NULL DEFAULT 'UGX',
  method TEXT NOT NULL CHECK(method IN ('cash', 'bank_transfer', 'mobile_money', 'cheque', 'other')),
  reference TEXT,
  notes TEXT,
  status TEXT NOT NULL CHECK(status IN ('draft', 'posted', 'void')) DEFAULT 'posted',
  void_reason TEXT,
  created_by_user_id INTEGER NOT NULL REFERENCES portal_users(id),
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);
CREATE INDEX IF NOT EXISTS idx_finance_payments_invoice ON finance_payments(related_invoice_id);
CREATE INDEX IF NOT EXISTS idx_finance_payments_status ON finance_payments(status);
CREATE INDEX IF NOT EXISTS idx_finance_payments_date ON finance_payments(date);

CREATE TABLE IF NOT EXISTS finance_payment_allocations (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  payment_id INTEGER NOT NULL REFERENCES finance_payments(id),
  invoice_id INTEGER NOT NULL REFERENCES finance_invoices(id),
  allocated_amount DOUBLE PRECISION NOT NULL DEFAULT 0,
  created_by_user_id INTEGER NOT NULL REFERENCES portal_users(id),
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);
CREATE INDEX IF NOT EXISTS idx_fin_alloc_payment ON finance_payment_allocations(payment_id);
CREATE INDEX IF NOT EXISTS idx_fin_alloc_invoice ON finance_payment_allocations(invoice_id);

CREATE TABLE IF NOT EXISTS finance_expenses (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  expense_number TEXT NOT NULL UNIQUE,
  vendor_name TEXT NOT NULL,
  date DATE NOT NULL,
  category TEXT NOT NULL DEFAULT 'Expense' CHECK(category = 'Expense'),
  subcategory TEXT,
  amount DOUBLE PRECISION NOT NULL DEFAULT 0,
  currency TEXT NOT NULL DEFAULT 'UGX',
  payment_method TEXT NOT NULL CHECK(payment_method IN ('cash', 'bank_transfer', 'mobile_money', 'cheque', 'other')),
  description TEXT NOT NULL,
  notes TEXT,
  status TEXT NOT NULL CHECK(status IN ('draft', 'submitted', 'posted', 'blocked_mismatch', 'void')) DEFAULT 'draft',
  void_reason TEXT,
  submitted_at TIMESTAMPTZ,
  submitted_by_user_id INTEGER REFERENCES portal_users(id),
  posted_at TIMESTAMPTZ,
  posted_by_user_id INTEGER REFERENCES portal_users(id),
  mismatch_override_reason TEXT,
  mismatch_override_by INTEGER REFERENCES portal_users(id),
  mismatch_override_at TIMESTAMPTZ,
  restricted_flag INTEGER DEFAULT 0,
  restricted_program TEXT,
  restricted_geo_scope TEXT,
  restricted_geo_id INTEGER,
  restriction_notes TEXT,
  created_by_user_id INTEGER NOT NULL REFERENCES portal_users(id),
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);
CREATE INDEX IF NOT EXISTS idx_finance_expenses_status ON finance_expenses(status);
CREATE INDEX IF NOT EXISTS idx_finance_expenses_date ON finance_expenses(date);

CREATE TABLE IF NOT EXISTS finance_transactions_ledger (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  txn_type TEXT NOT NULL CHECK(txn_type IN ('money_in', 'money_out')),
  category TEXT NOT NULL CHECK(category IN ('Donations', 'Contracts', 'Sponsorship', 'Expense')),
  display_category TEXT,
  subcategory TEXT,
  date DATE NOT NULL,
  currency TEXT NOT NULL DEFAULT 'UGX',
  amount DOUBLE PRECISION NOT NULL DEFAULT 0,
  counterparty_contact_id INTEGER REFERENCES finance_contacts(id),
  source_type TEXT NOT NULL CHECK(source_type IN ('receipt', 'invoice_payment', 'expense', 'adjustment')),
  source_id INTEGER NOT NULL,
  notes TEXT,
  evidence_file_ids_json TEXT NOT NULL DEFAULT '[]',
  posted_status TEXT NOT NULL CHECK(posted_status IN ('draft', 'posted', 'void')) DEFAULT 'posted',
  posted_at TIMESTAMPTZ,
  void_reason TEXT,
  created_by_user_id INTEGER NOT NULL REFERENCES portal_users(id),
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  restricted_flag INTEGER DEFAULT 0,
  restricted_program TEXT,
  restricted_geo_scope TEXT,
  restricted_geo_id INTEGER,
  restriction_notes TEXT
);
CREATE INDEX IF NOT EXISTS idx_finance_ledger_txn_type ON finance_transactions_ledger(txn_type);
CREATE INDEX IF NOT EXISTS idx_finance_ledger_category ON finance_transactions_ledger(category);
CREATE INDEX IF NOT EXISTS idx_finance_ledger_date ON finance_transactions_ledger(date);
CREATE INDEX IF NOT EXISTS idx_finance_ledger_source ON finance_transactions_ledger(source_type, source_id);

CREATE TABLE IF NOT EXISTS finance_expense_receipts (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  expense_id INTEGER NOT NULL REFERENCES finance_expenses(id) ON DELETE CASCADE,
  file_id INTEGER NOT NULL REFERENCES finance_files(id) ON DELETE CASCADE,
  file_url TEXT NOT NULL,
  file_hash_sha256 TEXT NOT NULL,
  vendor_name TEXT NOT NULL,
  receipt_date DATE NOT NULL,
  receipt_amount DOUBLE PRECISION NOT NULL DEFAULT 0,
  currency TEXT NOT NULL DEFAULT 'UGX',
  reference_no TEXT,
  uploaded_by_user_id INTEGER NOT NULL REFERENCES portal_users(id),
  uploaded_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);
CREATE INDEX IF NOT EXISTS idx_fin_exp_receipts_expense ON finance_expense_receipts(expense_id);
CREATE INDEX IF NOT EXISTS idx_fin_exp_receipts_hash ON finance_expense_receipts(file_hash_sha256);

CREATE TABLE IF NOT EXISTS finance_audit_exceptions (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  entity_type TEXT NOT NULL CHECK(entity_type IN ('expense', 'receipt', 'invoice', 'payment', 'ledger')),
  entity_id INTEGER NOT NULL,
  severity TEXT NOT NULL CHECK(severity IN ('low', 'medium', 'high')),
  rule_code TEXT NOT NULL,
  message TEXT NOT NULL,
  status TEXT NOT NULL CHECK(status IN ('open', 'acknowledged', 'resolved', 'overridden')) DEFAULT 'open',
  amount DOUBLE PRECISION,
  currency TEXT,
  created_by_user_id INTEGER REFERENCES portal_users(id),
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  resolved_at TIMESTAMPTZ,
  resolved_by_user_id INTEGER REFERENCES portal_users(id),
  resolution_notes TEXT
);
CREATE INDEX IF NOT EXISTS idx_fin_audit_exceptions_entity ON finance_audit_exceptions(entity_type, entity_id);
CREATE INDEX IF NOT EXISTS idx_fin_audit_exceptions_status ON finance_audit_exceptions(status);
CREATE INDEX IF NOT EXISTS idx_fin_audit_exceptions_rule ON finance_audit_exceptions(rule_code);

CREATE TABLE IF NOT EXISTS finance_txn_risk_scores (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  entity_type TEXT NOT NULL CHECK(entity_type IN ('expense', 'receipt', 'invoice', 'payment', 'ledger')),
  entity_id INTEGER NOT NULL,
  risk_score INTEGER NOT NULL DEFAULT 0,
  signals_json TEXT NOT NULL DEFAULT '[]',
  computed_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  UNIQUE(entity_type, entity_id)
);
CREATE INDEX IF NOT EXISTS idx_fin_risk_scores_entity ON finance_txn_risk_scores(entity_type, entity_id);

CREATE TABLE IF NOT EXISTS finance_statement_lines (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  account_type TEXT NOT NULL CHECK(account_type IN ('bank', 'cash', 'mobile_money')),
  date DATE NOT NULL,
  amount DOUBLE PRECISION NOT NULL DEFAULT 0,
  currency TEXT NOT NULL DEFAULT 'UGX',
  reference TEXT,
  description TEXT,
  match_status TEXT NOT NULL CHECK(match_status IN ('unmatched', 'matched', 'partial')) DEFAULT 'unmatched',
  matched_amount DOUBLE PRECISION NOT NULL DEFAULT 0,
  created_by_user_id INTEGER NOT NULL REFERENCES portal_users(id),
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);
CREATE INDEX IF NOT EXISTS idx_fin_stmt_lines_status ON finance_statement_lines(match_status);
CREATE INDEX IF NOT EXISTS idx_fin_stmt_lines_date ON finance_statement_lines(date);

CREATE TABLE IF NOT EXISTS finance_reconciliation_matches (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  statement_line_id INTEGER NOT NULL REFERENCES finance_statement_lines(id) ON DELETE CASCADE,
  ledger_txn_id INTEGER NOT NULL REFERENCES finance_transactions_ledger(id),
  matched_amount DOUBLE PRECISION NOT NULL DEFAULT 0,
  created_by_user_id INTEGER NOT NULL REFERENCES portal_users(id),
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);
CREATE INDEX IF NOT EXISTS idx_fin_recon_stmt ON finance_reconciliation_matches(statement_line_id);
CREATE INDEX IF NOT EXISTS idx_fin_recon_ledger ON finance_reconciliation_matches(ledger_txn_id);

CREATE TABLE IF NOT EXISTS finance_monthly_statements (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  month TEXT NOT NULL,
  period_type TEXT NOT NULL DEFAULT 'monthly' CHECK(period_type IN ('monthly', 'quarterly', 'fiscal_year')),
  currency TEXT NOT NULL DEFAULT 'UGX',
  total_money_in DOUBLE PRECISION NOT NULL DEFAULT 0,
  total_money_out DOUBLE PRECISION NOT NULL DEFAULT 0,
  net DOUBLE PRECISION NOT NULL DEFAULT 0,
  breakdown_json TEXT NOT NULL DEFAULT '{}',
  pdf_stored_path TEXT,
  pdf_file_id INTEGER,
  balance_sheet_pdf_file_id INTEGER,
  statement_of_financial_position_pdf_file_id INTEGER,
  income_statement_pdf_file_id INTEGER,
  generated_by_user_id INTEGER NOT NULL REFERENCES portal_users(id),
  generated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  UNIQUE(month, currency)
);
CREATE INDEX IF NOT EXISTS idx_finance_statements_month ON finance_monthly_statements(month, currency);

CREATE TABLE IF NOT EXISTS finance_email_logs (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  record_type TEXT NOT NULL CHECK(record_type IN ('invoice', 'receipt')),
  record_id INTEGER NOT NULL,
  to_email TEXT NOT NULL,
  cc_email TEXT,
  subject TEXT NOT NULL,
  status TEXT NOT NULL CHECK(status IN ('sent', 'failed', 'skipped')),
  provider_message TEXT,
  created_by_user_id INTEGER NOT NULL REFERENCES portal_users(id),
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);
CREATE INDEX IF NOT EXISTS idx_finance_email_logs_record ON finance_email_logs(record_type, record_id);

CREATE TABLE IF NOT EXISTS finance_public_snapshots (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  fy INTEGER NOT NULL,
  quarter TEXT,
  currency TEXT NOT NULL DEFAULT 'UGX',
  snapshot_type TEXT NOT NULL CHECK(snapshot_type IN ('fy', 'quarterly')),
  status TEXT NOT NULL CHECK(status IN ('draft', 'published', 'archived')) DEFAULT 'draft',
  total_income DOUBLE PRECISION NOT NULL DEFAULT 0,
  total_expenditure DOUBLE PRECISION NOT NULL DEFAULT 0,
  net DOUBLE PRECISION NOT NULL DEFAULT 0,
  program_pct DOUBLE PRECISION,
  admin_pct DOUBLE PRECISION,
  category_breakdown_json TEXT NOT NULL DEFAULT '[]',
  restricted_summary_json TEXT NOT NULL DEFAULT '[]',
  pdf_file_id INTEGER,
  stored_path TEXT,
  publish_confirmation TEXT,
  published_at TIMESTAMPTZ,
  published_by_user_id INTEGER REFERENCES portal_users(id),
  archived_at TIMESTAMPTZ,
  generated_by_user_id INTEGER NOT NULL REFERENCES portal_users(id),
  generated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  UNIQUE(fy, quarter, currency)
);

CREATE TABLE IF NOT EXISTS finance_budgets_monthly (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  month TEXT NOT NULL,
  currency TEXT NOT NULL DEFAULT 'UGX',
  subcategory TEXT NOT NULL,
  budget_amount DOUBLE PRECISION NOT NULL DEFAULT 0,
  created_by_user_id INTEGER NOT NULL REFERENCES portal_users(id),
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  UNIQUE(month, currency, subcategory)
);
CREATE INDEX IF NOT EXISTS idx_fin_budgets_month ON finance_budgets_monthly(month, currency);

CREATE TABLE IF NOT EXISTS finance_audited_statements (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  fy INTEGER NOT NULL,
  auditor_name TEXT,
  audit_completed_date DATE,
  status TEXT NOT NULL CHECK(status IN ('private_uploaded', 'published', 'archived')) DEFAULT 'private_uploaded',
  stored_path TEXT NOT NULL,
  original_filename TEXT NOT NULL,
  notes TEXT,
  publish_confirmation TEXT,
  published_at TIMESTAMPTZ,
  published_by_user_id INTEGER REFERENCES portal_users(id),
  archived_at TIMESTAMPTZ,
  uploaded_by_user_id INTEGER NOT NULL REFERENCES portal_users(id),
  uploaded_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);
