CREATE TABLE IF NOT EXISTS online_training_sessions (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  legacy_id INTEGER UNIQUE,
  title TEXT NOT NULL,
  agenda TEXT NOT NULL,
  objectives TEXT,
  program_tags_json TEXT NOT NULL DEFAULT '[]',
  scope_type TEXT NOT NULL DEFAULT 'country'
    CHECK(scope_type IN ('country', 'region', 'subregion', 'district', 'school')),
  scope_id TEXT,
  start_time TIMESTAMPTZ NOT NULL,
  end_time TIMESTAMPTZ NOT NULL,
  timezone TEXT NOT NULL DEFAULT 'Africa/Kampala',
  host_user_id INTEGER NOT NULL REFERENCES portal_users(id) ON DELETE RESTRICT,
  calendar_event_id TEXT,
  meet_join_url TEXT,
  conference_record_id TEXT,
  status TEXT NOT NULL DEFAULT 'draft'
    CHECK(status IN ('draft', 'scheduled', 'live', 'completed', 'canceled')),
  visibility TEXT NOT NULL DEFAULT 'private'
    CHECK(visibility IN ('private', 'schools', 'public')),
  created_by_user_id INTEGER NOT NULL REFERENCES portal_users(id) ON DELETE RESTRICT,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);
CREATE INDEX IF NOT EXISTS idx_online_training_sessions_start_time
  ON online_training_sessions(start_time DESC);
CREATE INDEX IF NOT EXISTS idx_online_training_sessions_status
  ON online_training_sessions(status, start_time DESC);
CREATE INDEX IF NOT EXISTS idx_online_training_sessions_host
  ON online_training_sessions(host_user_id, start_time DESC);
CREATE INDEX IF NOT EXISTS idx_online_training_sessions_calendar
  ON online_training_sessions(calendar_event_id);

CREATE TABLE IF NOT EXISTS online_training_participants (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  legacy_id INTEGER UNIQUE,
  session_id INTEGER NOT NULL REFERENCES online_training_sessions(id) ON DELETE CASCADE,
  school_id INTEGER REFERENCES schools_directory(id) ON DELETE SET NULL,
  teacher_user_id INTEGER,
  role TEXT NOT NULL DEFAULT 'attendee',
  attendance_status TEXT NOT NULL DEFAULT 'invited'
    CHECK(attendance_status IN ('invited', 'joined', 'attended', 'left', 'missed')),
  joined_at TIMESTAMPTZ,
  left_at TIMESTAMPTZ,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);
CREATE INDEX IF NOT EXISTS idx_online_training_participants_session
  ON online_training_participants(session_id);
CREATE INDEX IF NOT EXISTS idx_online_training_participants_school
  ON online_training_participants(school_id);

CREATE TABLE IF NOT EXISTS online_training_resources (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  legacy_id INTEGER UNIQUE,
  session_id INTEGER NOT NULL REFERENCES online_training_sessions(id) ON DELETE CASCADE,
  title TEXT NOT NULL,
  file_name TEXT,
  stored_path TEXT,
  mime_type TEXT,
  size_bytes INTEGER,
  external_url TEXT,
  visibility TEXT NOT NULL DEFAULT 'internal'
    CHECK(visibility IN ('internal', 'schools', 'public')),
  sort_order INTEGER NOT NULL DEFAULT 0,
  uploaded_by_user_id INTEGER REFERENCES portal_users(id) ON DELETE SET NULL,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);
CREATE INDEX IF NOT EXISTS idx_online_training_resources_session
  ON online_training_resources(session_id, sort_order ASC, id ASC);

CREATE TABLE IF NOT EXISTS online_training_artifacts (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  session_id INTEGER NOT NULL REFERENCES online_training_sessions(id) ON DELETE CASCADE,
  type TEXT NOT NULL
    CHECK(type IN ('recording', 'transcript', 'meet_notes', 'ai_notes')),
  source TEXT NOT NULL DEFAULT 'google_meet'
    CHECK(source IN ('google_meet', 'google_docs', 'ozeki_ai')),
  source_url TEXT,
  status TEXT NOT NULL DEFAULT 'pending'
    CHECK(status IN ('pending', 'processing', 'available', 'not_available', 'failed')),
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  UNIQUE(session_id, type)
);
CREATE INDEX IF NOT EXISTS idx_online_training_artifacts_session
  ON online_training_artifacts(session_id);

CREATE TABLE IF NOT EXISTS online_training_notes (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  session_id INTEGER NOT NULL UNIQUE REFERENCES online_training_sessions(id) ON DELETE CASCADE,
  facts_json TEXT NOT NULL,
  narrative_html TEXT NOT NULL,
  pdf_stored_path TEXT,
  ai_model TEXT,
  guardrail_version TEXT,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);
CREATE INDEX IF NOT EXISTS idx_online_training_notes_session
  ON online_training_notes(session_id);
