CREATE TABLE IF NOT EXISTS bookings (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  service TEXT NOT NULL,
  school_name TEXT NOT NULL,
  contact_name TEXT NOT NULL,
  email TEXT NOT NULL,
  phone TEXT NOT NULL,
  teachers INTEGER NOT NULL,
  grades TEXT NOT NULL,
  challenges TEXT NOT NULL,
  location TEXT NOT NULL,
  preferred_date TEXT NOT NULL,
  preferred_time TEXT NOT NULL,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS contacts (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  type TEXT NOT NULL,
  name TEXT NOT NULL,
  email TEXT NOT NULL,
  phone TEXT,
  organization TEXT,
  message TEXT NOT NULL,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS download_leads (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  resource_slug TEXT NOT NULL,
  name TEXT NOT NULL,
  email TEXT NOT NULL,
  organization TEXT,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS portal_resources (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  slug TEXT NOT NULL UNIQUE,
  title TEXT NOT NULL,
  description TEXT NOT NULL,
  grade TEXT NOT NULL CHECK(grade IN ('Nursery', 'P1-P2', 'P3-P4', 'P5-P7', 'All Primary')),
  skill TEXT NOT NULL CHECK(skill IN ('Phonics', 'Fluency', 'Comprehension', 'Assessment', 'Remedial', 'Writing')),
  type TEXT NOT NULL CHECK(type IN ('Toolkit', 'Lesson Plan', 'Assessment', 'Poster', 'Guide', 'Reader')),
  file_name TEXT,
  stored_path TEXT,
  mime_type TEXT,
  size_bytes INTEGER,
  external_url TEXT,
  download_label TEXT,
  section TEXT NOT NULL DEFAULT 'Resources Library',
  is_published BOOLEAN NOT NULL DEFAULT TRUE,
  created_by_user_id INTEGER NOT NULL REFERENCES portal_users(id),
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);
CREATE INDEX IF NOT EXISTS idx_portal_resources_created_at
  ON portal_resources(created_at DESC);
CREATE INDEX IF NOT EXISTS idx_portal_resources_published
  ON portal_resources(is_published, section, created_at DESC);

CREATE TABLE IF NOT EXISTS newsletter_subscribers (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name TEXT NOT NULL,
  email TEXT NOT NULL UNIQUE,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS newsletter_issues (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  slug TEXT NOT NULL UNIQUE,
  title TEXT NOT NULL,
  preheader TEXT NOT NULL DEFAULT '',
  html_content TEXT NOT NULL,
  plain_text TEXT NOT NULL DEFAULT '',
  status TEXT NOT NULL DEFAULT 'draft' CHECK(status IN ('draft', 'published')),
  auto_send_enabled BOOLEAN NOT NULL DEFAULT TRUE,
  published_at TIMESTAMPTZ,
  auto_sent_at TIMESTAMPTZ,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);
CREATE INDEX IF NOT EXISTS idx_newsletter_issues_status_published
  ON newsletter_issues(status, published_at DESC, created_at DESC);

CREATE TABLE IF NOT EXISTS newsletter_dispatch_logs (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  issue_id INTEGER NOT NULL REFERENCES newsletter_issues(id) ON DELETE CASCADE,
  recipient_email TEXT NOT NULL,
  status TEXT NOT NULL CHECK(status IN ('sent', 'failed', 'skipped')),
  provider_message TEXT,
  sent_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);
CREATE INDEX IF NOT EXISTS idx_newsletter_dispatch_issue
  ON newsletter_dispatch_logs(issue_id, sent_at DESC);

CREATE TABLE IF NOT EXISTS portal_blog_posts (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  slug TEXT NOT NULL UNIQUE,
  title TEXT NOT NULL,
  subtitle TEXT,
  excerpt TEXT NOT NULL,
  category TEXT NOT NULL,
  author_name TEXT NOT NULL,
  author_role TEXT NOT NULL,
  published_at TIMESTAMPTZ NOT NULL,
  read_time TEXT NOT NULL DEFAULT '5 min read',
  read_time_minutes INTEGER,
  tags_json TEXT NOT NULL DEFAULT '[]',
  sections_json TEXT NOT NULL DEFAULT '[]',
  body_blocks_json TEXT NOT NULL DEFAULT '[]',
  media_image_url TEXT,
  media_video_url TEXT,
  article_type TEXT,
  header_layout_type TEXT,
  featured_image_url TEXT,
  featured_image_alt TEXT,
  featured_image_caption TEXT,
  featured_image_credit TEXT,
  overlay_strength TEXT,
  hero_text_alignment TEXT,
  show_overlay_metadata BOOLEAN NOT NULL DEFAULT TRUE,
  show_overlay_share_icons BOOLEAN NOT NULL DEFAULT TRUE,
  primary_category TEXT,
  secondary_categories_json TEXT NOT NULL DEFAULT '[]',
  author_avatar_url TEXT,
  author_bio TEXT,
  toc_enabled BOOLEAN NOT NULL DEFAULT TRUE,
  spotlight_mode TEXT NOT NULL DEFAULT 'auto',
  spotlight_article_slugs_json TEXT NOT NULL DEFAULT '[]',
  show_spotlight_sidebar BOOLEAN NOT NULL DEFAULT TRUE,
  show_category_explorer BOOLEAN NOT NULL DEFAULT TRUE,
  show_newsletter_block BOOLEAN NOT NULL DEFAULT FALSE,
  cta_card_json TEXT NOT NULL DEFAULT '{}',
  seo_title TEXT,
  meta_description TEXT,
  social_image_url TEXT,
  canonical_url TEXT,
  featured_flag BOOLEAN NOT NULL DEFAULT FALSE,
  allow_comments BOOLEAN NOT NULL DEFAULT FALSE,
  publish_status TEXT NOT NULL DEFAULT 'draft' CHECK (publish_status IN ('draft', 'published')),
  created_by_user_id INTEGER NOT NULL REFERENCES portal_users(id),
  created_by_user_name TEXT NOT NULL,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);
CREATE INDEX IF NOT EXISTS idx_portal_blog_posts_status_published_at
  ON portal_blog_posts(publish_status, published_at DESC);

CREATE TABLE IF NOT EXISTS blog_post_views (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  post_slug TEXT NOT NULL,
  session_id TEXT NOT NULL,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  UNIQUE(post_slug, session_id)
);
CREATE INDEX IF NOT EXISTS idx_blog_post_views_slug
  ON blog_post_views(post_slug);

CREATE TABLE IF NOT EXISTS blog_post_likes (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  post_slug TEXT NOT NULL,
  session_id TEXT NOT NULL,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  UNIQUE(post_slug, session_id)
);
CREATE INDEX IF NOT EXISTS idx_blog_post_likes_slug
  ON blog_post_likes(post_slug);

CREATE TABLE IF NOT EXISTS blog_post_comments (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  post_slug TEXT NOT NULL,
  session_id TEXT,
  display_name TEXT,
  comment_text TEXT NOT NULL,
  status TEXT NOT NULL DEFAULT 'visible' CHECK (status IN ('visible', 'hidden', 'flagged')),
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);
CREATE INDEX IF NOT EXISTS idx_blog_post_comments_slug_created
  ON blog_post_comments(post_slug, created_at DESC);
