DO $$
BEGIN
  IF EXISTS (
    SELECT 1 FROM information_schema.columns
    WHERE table_name = 'audit_logs' AND column_name = 'id' AND is_identity = 'NO'
  ) THEN
    ALTER TABLE audit_logs ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY;
  END IF;
EXCEPTION WHEN duplicate_object THEN
  NULL;
END $$;

DO $$
DECLARE
  target record;
BEGIN
  FOR target IN
    SELECT *
    FROM (VALUES
      ('portal_records', 'id'),
      ('assessment_sessions', 'id'),
      ('assessment_session_results', 'id'),
      ('assessment_records', 'id'),
      ('portal_training_attendance', 'id'),
      ('lesson_evaluations', 'id'),
      ('lesson_evaluation_items', 'id'),
      ('story_activities', 'id'),
      ('story_anthologies', 'id'),
      ('coaching_visits', 'id'),
      ('visit_participants', 'id'),
      ('visit_demo', 'id'),
      ('visit_leadership_meeting', 'id'),
      ('school_support_status_snapshots', 'id'),
      ('teacher_support_status_snapshots', 'id'),
      ('assessment_item_responses', 'item_response_id')
    ) AS t(table_name, column_name)
  LOOP
    IF EXISTS (
      SELECT 1
      FROM information_schema.columns
      WHERE table_name = target.table_name
        AND column_name = target.column_name
        AND is_identity = 'NO'
    ) THEN
      BEGIN
        EXECUTE format(
          'ALTER TABLE %I ALTER COLUMN %I ADD GENERATED BY DEFAULT AS IDENTITY',
          target.table_name,
          target.column_name
        );
      EXCEPTION WHEN duplicate_object THEN
        NULL;
      END;
    END IF;
  END LOOP;
END $$;
