CREATE TABLE IF NOT EXISTS training_report_artifacts (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  report_code TEXT NOT NULL UNIQUE,
  scope_type TEXT NOT NULL,
  scope_value TEXT NOT NULL,
  period_start TEXT NOT NULL,
  period_end TEXT NOT NULL,
  facts_json TEXT NOT NULL,
  narrative_json TEXT NOT NULL,
  html_report TEXT NOT NULL,
  pdf_stored_path TEXT,
  generated_by_user_id INTEGER NOT NULL REFERENCES portal_users(id),
  generated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);
CREATE INDEX IF NOT EXISTS idx_training_report_artifacts_scope
  ON training_report_artifacts(scope_type, scope_value, generated_at DESC);

CREATE TABLE IF NOT EXISTS benchmark_profiles (
  benchmark_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name TEXT NOT NULL UNIQUE,
  effective_from_date TEXT NOT NULL,
  effective_to_date TEXT,
  notes TEXT,
  is_active BOOLEAN NOT NULL DEFAULT FALSE,
  created_by INTEGER NOT NULL REFERENCES portal_users(id),
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);
CREATE INDEX IF NOT EXISTS idx_benchmark_profiles_active
  ON benchmark_profiles(is_active, effective_from_date DESC);

CREATE TABLE IF NOT EXISTS benchmark_rules (
  rule_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  benchmark_id INTEGER NOT NULL REFERENCES benchmark_profiles(benchmark_id) ON DELETE CASCADE,
  grade TEXT NOT NULL,
  language TEXT NOT NULL,
  cwpm_bands_json TEXT NOT NULL,
  comprehension_proficient_rule_json TEXT NOT NULL,
  optional_accuracy_floor DOUBLE PRECISION,
  domain_proficiency_thresholds_json TEXT NOT NULL DEFAULT '{}',
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  UNIQUE(benchmark_id, grade, language)
);
CREATE INDEX IF NOT EXISTS idx_benchmark_rules_lookup
  ON benchmark_rules(benchmark_id, grade, language);

CREATE TABLE IF NOT EXISTS edu_audit_exceptions (
  exception_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  fingerprint TEXT NOT NULL UNIQUE,
  entity_type TEXT NOT NULL,
  entity_id TEXT NOT NULL,
  rule_code TEXT NOT NULL,
  severity TEXT NOT NULL CHECK(severity IN ('low', 'medium', 'high')),
  message TEXT NOT NULL,
  status TEXT NOT NULL DEFAULT 'open' CHECK(status IN ('open', 'resolved', 'overridden')),
  scope_type TEXT NOT NULL,
  scope_id TEXT NOT NULL,
  period_key TEXT NOT NULL,
  source_run_id TEXT,
  auto_generated BOOLEAN NOT NULL DEFAULT TRUE,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  resolved_by INTEGER REFERENCES portal_users(id),
  resolved_at TIMESTAMPTZ,
  resolution_notes TEXT
);
CREATE INDEX IF NOT EXISTS idx_edu_audit_exceptions_scope
  ON edu_audit_exceptions(scope_type, scope_id, status, severity);
CREATE INDEX IF NOT EXISTS idx_edu_audit_exceptions_rule
  ON edu_audit_exceptions(rule_code, status);

CREATE TABLE IF NOT EXISTS edu_data_quality_summary (
  scope_type TEXT NOT NULL,
  scope_id TEXT NOT NULL,
  period_key TEXT NOT NULL,
  completeness_pct DOUBLE PRECISION NOT NULL,
  coverage_json TEXT NOT NULL,
  exception_counts_json TEXT NOT NULL,
  last_updated TIMESTAMPTZ NOT NULL,
  PRIMARY KEY(scope_type, scope_id, period_key)
);

CREATE TABLE IF NOT EXISTS edu_priority_queue_assignments (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  school_id INTEGER NOT NULL REFERENCES schools_directory(id) ON DELETE CASCADE,
  period_key TEXT NOT NULL,
  owner_user_id INTEGER NOT NULL REFERENCES portal_users(id),
  notes TEXT,
  assigned_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  UNIQUE(school_id, period_key)
);

CREATE TABLE IF NOT EXISTS intervention_plan (
  plan_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  scope_type TEXT NOT NULL CHECK(scope_type IN ('school', 'district')),
  scope_id TEXT NOT NULL,
  school_id INTEGER REFERENCES schools_directory(id) ON DELETE SET NULL,
  district TEXT,
  title TEXT NOT NULL,
  created_by INTEGER NOT NULL REFERENCES portal_users(id),
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  status TEXT NOT NULL DEFAULT 'planned' CHECK(status IN ('planned', 'in_progress', 'completed', 'paused')),
  target_metrics_json TEXT NOT NULL DEFAULT '{}',
  start_date TEXT,
  end_date TEXT,
  notes TEXT
);
CREATE INDEX IF NOT EXISTS idx_intervention_plan_scope
  ON intervention_plan(scope_type, scope_id, status);

CREATE TABLE IF NOT EXISTS intervention_actions (
  action_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  plan_id INTEGER NOT NULL REFERENCES intervention_plan(plan_id) ON DELETE CASCADE,
  action_type TEXT NOT NULL,
  owner_user_id INTEGER NOT NULL REFERENCES portal_users(id),
  due_date TEXT,
  status TEXT NOT NULL DEFAULT 'planned' CHECK(status IN ('planned', 'in_progress', 'completed', 'paused')),
  visit_id INTEGER,
  training_id INTEGER,
  assessment_id INTEGER,
  story_activity_id INTEGER,
  outcome_notes TEXT,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);
CREATE INDEX IF NOT EXISTS idx_intervention_actions_plan
  ON intervention_actions(plan_id, status, due_date);

CREATE TABLE IF NOT EXISTS national_report_packs (
  report_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  report_code TEXT NOT NULL UNIQUE,
  preset TEXT NOT NULL,
  scope_type TEXT NOT NULL,
  scope_id TEXT NOT NULL,
  period_start TEXT NOT NULL,
  period_end TEXT NOT NULL,
  facts_json TEXT NOT NULL,
  narrative_json TEXT NOT NULL,
  html_report TEXT NOT NULL,
  pdf_stored_path TEXT,
  generated_by_user_id INTEGER NOT NULL REFERENCES portal_users(id),
  generated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);
CREATE INDEX IF NOT EXISTS idx_national_report_packs_scope
  ON national_report_packs(scope_type, scope_id, preset, generated_at DESC);

CREATE TABLE IF NOT EXISTS partner_api_clients (
  client_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  partner_name TEXT NOT NULL,
  api_key_hash TEXT NOT NULL UNIQUE,
  allowed_scope_type TEXT NOT NULL,
  allowed_scope_ids_json TEXT NOT NULL,
  active BOOLEAN NOT NULL DEFAULT TRUE,
  created_by INTEGER NOT NULL REFERENCES portal_users(id),
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  last_used_at TIMESTAMPTZ
);

CREATE TABLE IF NOT EXISTS partner_export_audit_logs (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  client_id INTEGER REFERENCES partner_api_clients(client_id),
  partner_name TEXT NOT NULL,
  endpoint TEXT NOT NULL,
  scope_type TEXT NOT NULL,
  scope_id TEXT NOT NULL,
  format TEXT NOT NULL,
  actor_user_id INTEGER REFERENCES portal_users(id),
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);
CREATE INDEX IF NOT EXISTS idx_partner_export_logs_scope
  ON partner_export_audit_logs(scope_type, scope_id, created_at DESC);
