ALTER TABLE learner_roster ADD COLUMN IF NOT EXISTS internal_child_id TEXT;
ALTER TABLE learner_roster ADD COLUMN IF NOT EXISTS consent_flag BOOLEAN NOT NULL DEFAULT FALSE;

ALTER TABLE assessment_records ADD COLUMN IF NOT EXISTS assessment_model_computed_at TIMESTAMPTZ;
ALTER TABLE assessment_records ADD COLUMN IF NOT EXISTS phonemic_awareness_score_raw DOUBLE PRECISION;
ALTER TABLE assessment_records ADD COLUMN IF NOT EXISTS phonemic_awareness_accuracy DOUBLE PRECISION;
ALTER TABLE assessment_records ADD COLUMN IF NOT EXISTS phonemic_awareness_latency_avg DOUBLE PRECISION;
ALTER TABLE assessment_records ADD COLUMN IF NOT EXISTS phonemic_awareness_attempts_avg DOUBLE PRECISION;
ALTER TABLE assessment_records ADD COLUMN IF NOT EXISTS phonemic_awareness_support_usage_rate DOUBLE PRECISION;
ALTER TABLE assessment_records ADD COLUMN IF NOT EXISTS grapheme_phoneme_correspondence_score_raw DOUBLE PRECISION;
ALTER TABLE assessment_records ADD COLUMN IF NOT EXISTS grapheme_phoneme_correspondence_accuracy DOUBLE PRECISION;
ALTER TABLE assessment_records ADD COLUMN IF NOT EXISTS grapheme_phoneme_correspondence_latency_avg DOUBLE PRECISION;
ALTER TABLE assessment_records ADD COLUMN IF NOT EXISTS grapheme_phoneme_correspondence_attempts_avg DOUBLE PRECISION;
ALTER TABLE assessment_records ADD COLUMN IF NOT EXISTS grapheme_phoneme_correspondence_support_usage_rate DOUBLE PRECISION;
ALTER TABLE assessment_records ADD COLUMN IF NOT EXISTS blending_decoding_score_raw DOUBLE PRECISION;
ALTER TABLE assessment_records ADD COLUMN IF NOT EXISTS blending_decoding_accuracy DOUBLE PRECISION;
ALTER TABLE assessment_records ADD COLUMN IF NOT EXISTS blending_decoding_latency_avg DOUBLE PRECISION;
ALTER TABLE assessment_records ADD COLUMN IF NOT EXISTS blending_decoding_attempts_avg DOUBLE PRECISION;
ALTER TABLE assessment_records ADD COLUMN IF NOT EXISTS blending_decoding_support_usage_rate DOUBLE PRECISION;
ALTER TABLE assessment_records ADD COLUMN IF NOT EXISTS word_recognition_fluency_score_raw DOUBLE PRECISION;
ALTER TABLE assessment_records ADD COLUMN IF NOT EXISTS word_recognition_fluency_accuracy DOUBLE PRECISION;
ALTER TABLE assessment_records ADD COLUMN IF NOT EXISTS word_recognition_fluency_latency_avg DOUBLE PRECISION;
ALTER TABLE assessment_records ADD COLUMN IF NOT EXISTS word_recognition_fluency_attempts_avg DOUBLE PRECISION;
ALTER TABLE assessment_records ADD COLUMN IF NOT EXISTS word_recognition_fluency_support_usage_rate DOUBLE PRECISION;
ALTER TABLE assessment_records ADD COLUMN IF NOT EXISTS sentence_paragraph_construction_score_raw DOUBLE PRECISION;
ALTER TABLE assessment_records ADD COLUMN IF NOT EXISTS sentence_paragraph_construction_accuracy DOUBLE PRECISION;
ALTER TABLE assessment_records ADD COLUMN IF NOT EXISTS sentence_paragraph_construction_latency_avg DOUBLE PRECISION;
ALTER TABLE assessment_records ADD COLUMN IF NOT EXISTS sentence_paragraph_construction_attempts_avg DOUBLE PRECISION;
ALTER TABLE assessment_records ADD COLUMN IF NOT EXISTS sentence_paragraph_construction_support_usage_rate DOUBLE PRECISION;
ALTER TABLE assessment_records ADD COLUMN IF NOT EXISTS comprehension_score_raw DOUBLE PRECISION;
ALTER TABLE assessment_records ADD COLUMN IF NOT EXISTS comprehension_accuracy DOUBLE PRECISION;
ALTER TABLE assessment_records ADD COLUMN IF NOT EXISTS comprehension_latency_avg DOUBLE PRECISION;
ALTER TABLE assessment_records ADD COLUMN IF NOT EXISTS comprehension_attempts_avg DOUBLE PRECISION;
ALTER TABLE assessment_records ADD COLUMN IF NOT EXISTS comprehension_support_usage_rate DOUBLE PRECISION;

DO $$
DECLARE
  target record;
BEGIN
  FOR target IN
    SELECT *
    FROM (VALUES
      ('school_contacts', 'contact_id'),
      ('school_learners', 'learner_id'),
      ('teacher_roster', 'id'),
      ('learner_roster', 'id')
    ) AS t(table_name, column_name)
  LOOP
    IF EXISTS (
      SELECT 1
      FROM information_schema.columns
      WHERE table_name = target.table_name
        AND column_name = target.column_name
        AND is_identity = 'NO'
    ) THEN
      BEGIN
        EXECUTE format(
          'ALTER TABLE %I ALTER COLUMN %I ADD GENERATED BY DEFAULT AS IDENTITY',
          target.table_name,
          target.column_name
        );
      EXCEPTION WHEN duplicate_object THEN
        NULL;
      END;
    END IF;
  END LOOP;
END $$;
