CREATE TABLE IF NOT EXISTS graduation_settings (
  id INTEGER PRIMARY KEY CHECK (id = 1),
  graduation_enabled BOOLEAN NOT NULL DEFAULT TRUE,
  target_domain_proficiency_pct DOUBLE PRECISION NOT NULL DEFAULT 90,
  required_domains_json TEXT NOT NULL DEFAULT '["letter_sounds","decoding","fluency","comprehension"]',
  required_reading_level TEXT NOT NULL DEFAULT 'Fluent',
  required_fluent_pct DOUBLE PRECISION NOT NULL DEFAULT 100,
  min_published_stories INTEGER NOT NULL DEFAULT 15,
  target_teaching_quality_pct DOUBLE PRECISION NOT NULL DEFAULT 90,
  require_teaching_domains BOOLEAN NOT NULL DEFAULT FALSE,
  latest_assessment_required BOOLEAN NOT NULL DEFAULT TRUE,
  latest_evaluation_required BOOLEAN NOT NULL DEFAULT TRUE,
  assessment_cycle_mode TEXT NOT NULL DEFAULT 'latest_or_endline'
    CHECK (assessment_cycle_mode IN ('latest_or_endline', 'latest', 'endline')),
  dismiss_snooze_days INTEGER NOT NULL DEFAULT 30,
  criteria_version TEXT NOT NULL DEFAULT 'GRAD-v1.0',
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  min_learners_assessed_n INTEGER NOT NULL DEFAULT 30,
  target_grades_json TEXT NOT NULL DEFAULT '["P2","P3","P4"]',
  min_teacher_evaluations_total INTEGER NOT NULL DEFAULT 3,
  min_evaluations_per_reading_teacher INTEGER NOT NULL DEFAULT 2,
  data_completeness_threshold DOUBLE PRECISION NOT NULL DEFAULT 80,
  require_sustainability_validation BOOLEAN NOT NULL DEFAULT TRUE,
  sustainability_checklist_json TEXT NOT NULL DEFAULT '["School reading routines are embedded and observed consistently","Head teacher actively leads literacy instruction monitoring","Teachers demonstrate independent lesson planning for phonics","Community/parent engagement supports reading at home","Reading materials are available and actively used in classrooms","School has a succession plan for sustaining reading outcomes"]'
);

CREATE TABLE IF NOT EXISTS school_graduation_eligibility_cache (
  school_id INTEGER PRIMARY KEY REFERENCES schools_directory(id) ON DELETE CASCADE,
  is_eligible BOOLEAN NOT NULL DEFAULT FALSE,
  domains_ok BOOLEAN NOT NULL DEFAULT FALSE,
  reading_levels_ok BOOLEAN NOT NULL DEFAULT FALSE,
  stories_ok BOOLEAN NOT NULL DEFAULT FALSE,
  teaching_ok BOOLEAN NOT NULL DEFAULT FALSE,
  domain_values_json TEXT NOT NULL DEFAULT '[]',
  scorecard_json TEXT NOT NULL DEFAULT '{}',
  missing_data_json TEXT NOT NULL DEFAULT '[]',
  fluent_pct DOUBLE PRECISION,
  published_story_count INTEGER NOT NULL DEFAULT 0,
  teaching_quality_pct DOUBLE PRECISION,
  assessment_sample_size INTEGER NOT NULL DEFAULT 0,
  evaluations_count INTEGER NOT NULL DEFAULT 0,
  criteria_version TEXT NOT NULL DEFAULT 'GRAD-v1.0',
  last_updated_source TEXT,
  computed_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  evidence_gates_ok BOOLEAN NOT NULL DEFAULT FALSE,
  sustainability_status TEXT NOT NULL DEFAULT 'pending',
  validation_pass_count INTEGER NOT NULL DEFAULT 0
);
CREATE INDEX IF NOT EXISTS idx_school_graduation_cache_eligible
  ON school_graduation_eligibility_cache(is_eligible, computed_at DESC);

CREATE TABLE IF NOT EXISTS school_graduation_workflow (
  school_id INTEGER PRIMARY KEY REFERENCES schools_directory(id) ON DELETE CASCADE,
  state TEXT NOT NULL DEFAULT 'pending'
    CHECK (state IN ('pending', 'kept_supporting', 'needs_review', 'graduated', 'monitoring')),
  snoozed_until DATE,
  assigned_supervisor_user_id INTEGER REFERENCES portal_users(id),
  reason TEXT,
  updated_by_user_id INTEGER REFERENCES portal_users(id),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  checklist_answers_json TEXT,
  checklist_completed_at TIMESTAMPTZ,
  checklist_completed_by_user_id INTEGER REFERENCES portal_users(id)
);
CREATE INDEX IF NOT EXISTS idx_school_graduation_workflow_state
  ON school_graduation_workflow(state, snoozed_until);

CREATE TABLE IF NOT EXISTS school_graduation_validation_history (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  school_id INTEGER NOT NULL REFERENCES schools_directory(id) ON DELETE CASCADE,
  pass_number INTEGER NOT NULL,
  scorecard_json TEXT NOT NULL,
  assessment_event_label TEXT,
  computed_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);
CREATE INDEX IF NOT EXISTS idx_grad_validation_history_school
  ON school_graduation_validation_history(school_id, pass_number);
