DO $$
DECLARE
  target record;
BEGIN
  FOR target IN
    SELECT *
    FROM (VALUES
      ('bookings', 'id'),
      ('contacts', 'id'),
      ('download_leads', 'id'),
      ('newsletter_subscribers', 'id')
    ) AS t(table_name, column_name)
  LOOP
    IF EXISTS (
      SELECT 1
      FROM information_schema.columns
      WHERE table_name = target.table_name
        AND column_name = target.column_name
        AND is_identity = 'NO'
        AND column_default IS NULL
    ) THEN
      BEGIN
        EXECUTE format(
          'ALTER TABLE %I ALTER COLUMN %I ADD GENERATED BY DEFAULT AS IDENTITY',
          target.table_name,
          target.column_name
        );
      EXCEPTION WHEN duplicate_object THEN
        NULL;
      END;
    END IF;
  END LOOP;
END $$;
