-- Finance V2 Core Schema expansion
-- Enforces referential integrity and mandatory linkages for fund accounting, budgeting, and grants.

-- 1. Base Master Data Expansion
CREATE TABLE IF NOT EXISTS finance_funds (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  code TEXT NOT NULL UNIQUE,
  name TEXT NOT NULL,
  fund_type TEXT NOT NULL CHECK(fund_type IN ('restricted', 'unrestricted', 'designated')),
  description TEXT,
  is_active INTEGER NOT NULL DEFAULT 1,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS finance_branches (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name TEXT NOT NULL UNIQUE,
  location TEXT,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS finance_departments (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  code TEXT NOT NULL UNIQUE,
  name TEXT NOT NULL,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS finance_programs (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  code TEXT NOT NULL UNIQUE,
  name TEXT NOT NULL,
  description TEXT,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS finance_projects (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  code TEXT NOT NULL UNIQUE,
  name TEXT NOT NULL,
  program_id INTEGER REFERENCES finance_programs(id),
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

-- 2. Grant Management
CREATE TABLE IF NOT EXISTS finance_grants (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  code TEXT NOT NULL UNIQUE,
  name TEXT NOT NULL,
  grantor_contact_id INTEGER NOT NULL REFERENCES finance_contacts(id),
  fund_id INTEGER NOT NULL REFERENCES finance_funds(id),
  total_award_amount DOUBLE PRECISION NOT NULL,
  currency TEXT NOT NULL DEFAULT 'UGX',
  start_date DATE NOT NULL,
  end_date DATE NOT NULL,
  status TEXT NOT NULL CHECK(status IN ('active', 'closed', 'pending')),
  notes TEXT,
  compliance_notes TEXT,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

-- 3. Chart of Accounts & GL
CREATE TABLE IF NOT EXISTS finance_chart_of_accounts (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  account_code TEXT NOT NULL UNIQUE,
  account_name TEXT NOT NULL,
  account_type TEXT NOT NULL CHECK(account_type IN ('asset', 'liability', 'equity', 'income', 'expense')),
  is_active INTEGER NOT NULL DEFAULT 1,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS finance_journal_entries (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  entry_number TEXT NOT NULL UNIQUE, -- e.g. JE-2026-000001
  entry_date DATE NOT NULL,
  description TEXT,
  source_type TEXT NOT NULL, -- 'manual', 'donation', 'bill', 'expense', 'asset_depreciation'
  source_id INTEGER,
  status TEXT NOT NULL CHECK(status IN ('draft', 'posted', 'reversed')),
  posted_at TIMESTAMPTZ,
  posted_by_user_id INTEGER REFERENCES portal_users(id),
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS finance_journal_lines (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  journal_id INTEGER NOT NULL REFERENCES finance_journal_entries(id) ON DELETE CASCADE,
  account_id INTEGER NOT NULL REFERENCES finance_chart_of_accounts(id),
  debit DOUBLE PRECISION NOT NULL DEFAULT 0,
  credit DOUBLE PRECISION NOT NULL DEFAULT 0,
  fund_id INTEGER NOT NULL REFERENCES finance_funds(id),
  department_id INTEGER REFERENCES finance_departments(id),
  program_id INTEGER REFERENCES finance_programs(id),
  project_id INTEGER REFERENCES finance_projects(id),
  grant_id INTEGER REFERENCES finance_grants(id),
  branch_id INTEGER REFERENCES finance_branches(id),
  description TEXT,
  CHECK (debit >= 0 AND credit >= 0 AND (debit > 0 OR credit > 0)),
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

-- 4. Budgeting
CREATE TABLE IF NOT EXISTS finance_budget_plans (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  fiscal_year INTEGER NOT NULL,
  title TEXT NOT NULL,
  status TEXT NOT NULL CHECK(status IN ('draft', 'active', 'closed')),
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS finance_budget_lines (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  plan_id INTEGER NOT NULL REFERENCES finance_budget_plans(id),
  account_id INTEGER NOT NULL REFERENCES finance_chart_of_accounts(id),
  fund_id INTEGER NOT NULL REFERENCES finance_funds(id),
  department_id INTEGER REFERENCES finance_departments(id),
  program_id INTEGER REFERENCES finance_programs(id),
  project_id INTEGER REFERENCES finance_projects(id),
  grant_id INTEGER REFERENCES finance_grants(id),
  amount DOUBLE PRECISION NOT NULL DEFAULT 0,
  fiscal_period TEXT NOT NULL, -- e.g. '2026-03'
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

-- 5. Asset Management
CREATE TABLE IF NOT EXISTS finance_assets (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  asset_code TEXT NOT NULL UNIQUE,
  name TEXT NOT NULL,
  acquisition_date DATE NOT NULL,
  purchase_value DOUBLE PRECISION NOT NULL,
  currency TEXT NOT NULL DEFAULT 'UGX',
  useful_life_months INTEGER NOT NULL,
  residual_value DOUBLE PRECISION NOT NULL DEFAULT 0,
  depreciation_method TEXT NOT NULL CHECK(depreciation_method IN ('straight_line', 'none')),
  vendor_id INTEGER REFERENCES finance_contacts(id),
  fund_id INTEGER REFERENCES finance_funds(id),
  source_txn_id INTEGER, -- Link to payment or bill if available
  status TEXT NOT NULL CHECK(status IN ('active', 'disposed')),
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

-- 6. Approvals & Audit
CREATE TABLE IF NOT EXISTS finance_approval_workflows (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  entity_type TEXT NOT NULL, -- 'expense', 'bill', 'journal_entry'
  entity_id INTEGER NOT NULL,
  status TEXT NOT NULL CHECK(status IN ('pending', 'approved', 'rejected')),
  current_step INTEGER NOT NULL DEFAULT 1,
  required_steps INTEGER NOT NULL DEFAULT 1,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS finance_approval_logs (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  workflow_id INTEGER NOT NULL REFERENCES finance_approval_workflows(id),
  user_id INTEGER NOT NULL REFERENCES portal_users(id),
  action TEXT NOT NULL CHECK(action IN ('approve', 'reject')),
  notes TEXT,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS finance_audit_trail (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  table_name TEXT NOT NULL,
  row_id INTEGER NOT NULL,
  action TEXT NOT NULL CHECK(action IN ('create', 'update', 'delete', 'post', 'reverse', 'generate_pdf')),
  user_id INTEGER NOT NULL REFERENCES portal_users(id),
  payload_before JSONB,
  payload_after JSONB,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

-- 7. Document Linkage (Centralized)
CREATE TABLE IF NOT EXISTS finance_generated_documents (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  document_number TEXT NOT NULL UNIQUE,
  document_type TEXT NOT NULL, -- 'receipt', 'invoice', 'voucher', 'report'
  source_type TEXT NOT NULL,
  source_id INTEGER NOT NULL,
  file_id INTEGER REFERENCES finance_files(id),
  stored_path TEXT,
  generated_by_user_id INTEGER NOT NULL REFERENCES portal_users(id),
  metadata JSONB,
  is_immutable INTEGER NOT NULL DEFAULT 1,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

-- Add missing columns to existing tables for linkage
ALTER TABLE finance_contacts ADD COLUMN IF NOT EXISTS is_vendor INTEGER DEFAULT 0;
ALTER TABLE finance_contacts ADD COLUMN IF NOT EXISTS is_customer INTEGER DEFAULT 0;
ALTER TABLE finance_contacts ADD COLUMN IF NOT EXISTS organization_name TEXT;

-- Update expenses for fund linkage
ALTER TABLE finance_expenses ADD COLUMN IF NOT EXISTS fund_id INTEGER REFERENCES finance_funds(id);
ALTER TABLE finance_expenses ADD COLUMN IF NOT EXISTS department_id INTEGER REFERENCES finance_departments(id);
ALTER TABLE finance_expenses ADD COLUMN IF NOT EXISTS program_id INTEGER REFERENCES finance_programs(id);
ALTER TABLE finance_expenses ADD COLUMN IF NOT EXISTS project_id INTEGER REFERENCES finance_projects(id);
ALTER TABLE finance_expenses ADD COLUMN IF NOT EXISTS grant_id INTEGER REFERENCES finance_grants(id);
ALTER TABLE finance_expenses ADD COLUMN IF NOT EXISTS vendor_id INTEGER REFERENCES finance_contacts(id);

-- Update receipts for fund linkage
ALTER TABLE finance_receipts ADD COLUMN IF NOT EXISTS fund_id INTEGER REFERENCES finance_funds(id);
ALTER TABLE finance_receipts ADD COLUMN IF NOT EXISTS campaign_id INTEGER;
ALTER TABLE finance_receipts ADD COLUMN IF NOT EXISTS program_id INTEGER REFERENCES finance_programs(id);
ALTER TABLE finance_receipts ADD COLUMN IF NOT EXISTS grant_id INTEGER REFERENCES finance_grants(id);
