CREATE TABLE IF NOT EXISTS cost_entries (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  scope_type TEXT NOT NULL CHECK(scope_type IN ('country', 'region', 'district', 'school')),
  scope_value TEXT NOT NULL,
  period TEXT NOT NULL,
  category TEXT NOT NULL,
  amount DOUBLE PRECISION NOT NULL DEFAULT 0,
  notes TEXT,
  created_by_user_id INTEGER NOT NULL REFERENCES portal_users(id),
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);
CREATE INDEX IF NOT EXISTS idx_cost_entries_scope
  ON cost_entries(scope_type, scope_value, period);

CREATE TABLE IF NOT EXISTS intervention_groups (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  school_id INTEGER NOT NULL REFERENCES schools_directory(id) ON DELETE CASCADE,
  grade TEXT NOT NULL,
  target_skill TEXT NOT NULL,
  learners_json TEXT NOT NULL DEFAULT '[]',
  schedule TEXT,
  start_date DATE NOT NULL,
  end_date DATE,
  created_by_user_id INTEGER NOT NULL REFERENCES portal_users(id),
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);
CREATE INDEX IF NOT EXISTS idx_intervention_groups_school
  ON intervention_groups(school_id);

CREATE TABLE IF NOT EXISTS intervention_sessions (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  group_id INTEGER NOT NULL REFERENCES intervention_groups(id) ON DELETE CASCADE,
  date DATE NOT NULL,
  attendance INTEGER NOT NULL DEFAULT 0,
  skills_practiced TEXT NOT NULL,
  quick_check_score DOUBLE PRECISION,
  notes TEXT,
  created_by_user_id INTEGER NOT NULL REFERENCES portal_users(id),
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);
CREATE INDEX IF NOT EXISTS idx_intervention_sessions_group
  ON intervention_sessions(group_id, date DESC);

CREATE TABLE IF NOT EXISTS consent_records (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  school_id INTEGER NOT NULL REFERENCES schools_directory(id) ON DELETE CASCADE,
  consent_type TEXT NOT NULL CHECK(consent_type IN ('photo', 'video', 'story')),
  source TEXT NOT NULL,
  date DATE NOT NULL,
  allowed_usage TEXT NOT NULL CHECK(allowed_usage IN ('public', 'partner', 'internal')),
  linked_files TEXT NOT NULL DEFAULT '',
  expiry_date DATE,
  created_by_user_id INTEGER NOT NULL REFERENCES portal_users(id),
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);
CREATE INDEX IF NOT EXISTS idx_consent_records_school
  ON consent_records(school_id, date DESC);
