CREATE TABLE IF NOT EXISTS impact_reports (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  report_code TEXT NOT NULL UNIQUE,
  title TEXT NOT NULL,
  partner_name TEXT,
  report_type TEXT NOT NULL,
  report_category TEXT,
  scope_type TEXT NOT NULL,
  scope_value TEXT NOT NULL,
  region_id TEXT,
  sub_region_id TEXT,
  district_id TEXT,
  school_id INTEGER REFERENCES schools_directory(id) ON DELETE SET NULL,
  period_type TEXT NOT NULL DEFAULT 'FY',
  period_start TEXT NOT NULL,
  period_end TEXT NOT NULL,
  programs_json JSONB NOT NULL DEFAULT '[]'::jsonb,
  fact_pack_json JSONB NOT NULL DEFAULT '{}'::jsonb,
  narrative_json JSONB NOT NULL DEFAULT '{}'::jsonb,
  audience TEXT NOT NULL DEFAULT 'Public-safe',
  output TEXT NOT NULL DEFAULT 'PDF',
  status TEXT NOT NULL DEFAULT 'Generated',
  is_public BOOLEAN NOT NULL DEFAULT TRUE,
  version TEXT NOT NULL DEFAULT 'v1.0',
  generated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  view_count INTEGER NOT NULL DEFAULT 0,
  download_count INTEGER NOT NULL DEFAULT 0,
  created_by_user_id INTEGER NOT NULL REFERENCES portal_users(id),
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_impact_reports_generated_at
  ON impact_reports(generated_at DESC);

CREATE INDEX IF NOT EXISTS idx_impact_reports_public
  ON impact_reports(is_public, generated_at DESC);

CREATE INDEX IF NOT EXISTS idx_impact_reports_scope
  ON impact_reports(scope_type, scope_value);

CREATE INDEX IF NOT EXISTS idx_impact_reports_scope_geo
  ON impact_reports(region_id, sub_region_id, district_id, school_id);

CREATE INDEX IF NOT EXISTS idx_impact_reports_category
  ON impact_reports(report_category, generated_at DESC);

CREATE INDEX IF NOT EXISTS idx_impact_reports_period_type
  ON impact_reports(period_type);

CREATE INDEX IF NOT EXISTS idx_impact_reports_audience
  ON impact_reports(audience);

CREATE INDEX IF NOT EXISTS idx_impact_reports_output
  ON impact_reports(output);
