CREATE TABLE IF NOT EXISTS portal_leadership_team_members (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  section TEXT NOT NULL CHECK (section IN ('board', 'staff', 'volunteer')),
  name TEXT NOT NULL,
  role TEXT NOT NULL,
  biography TEXT NOT NULL,
  background TEXT NOT NULL,
  career TEXT NOT NULL,
  photo_file_name TEXT,
  photo_stored_path TEXT,
  photo_mime_type TEXT,
  photo_size_bytes INTEGER,
  photo_alt TEXT,
  sort_order INTEGER NOT NULL DEFAULT 0,
  is_published BOOLEAN NOT NULL DEFAULT TRUE,
  created_by_user_id INTEGER NOT NULL REFERENCES portal_users(id),
  updated_by_user_id INTEGER NOT NULL REFERENCES portal_users(id),
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);
CREATE INDEX IF NOT EXISTS idx_portal_leadership_team_section
  ON portal_leadership_team_members(section, sort_order ASC, updated_at DESC);
CREATE INDEX IF NOT EXISTS idx_portal_leadership_team_published
  ON portal_leadership_team_members(is_published);

CREATE TABLE IF NOT EXISTS portal_core_values (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  title TEXT NOT NULL,
  description TEXT NOT NULL,
  sort_order INTEGER NOT NULL DEFAULT 0,
  is_published BOOLEAN NOT NULL DEFAULT TRUE,
  created_by_user_id INTEGER NOT NULL REFERENCES portal_users(id),
  updated_by_user_id INTEGER NOT NULL REFERENCES portal_users(id),
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);
CREATE INDEX IF NOT EXISTS idx_portal_core_values_sort
  ON portal_core_values(sort_order ASC, updated_at DESC);
CREATE INDEX IF NOT EXISTS idx_portal_core_values_published
  ON portal_core_values(is_published);

CREATE TABLE IF NOT EXISTS story_views (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  story_id INTEGER NOT NULL REFERENCES story_library(id) ON DELETE CASCADE,
  session_id TEXT NOT NULL,
  user_id INTEGER REFERENCES portal_users(id) ON DELETE SET NULL,
  geo_hint TEXT,
  duration_seconds INTEGER,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);
CREATE INDEX IF NOT EXISTS idx_story_views_story
  ON story_views(story_id, created_at DESC);

CREATE TABLE IF NOT EXISTS story_ratings (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  story_id INTEGER NOT NULL REFERENCES story_library(id) ON DELETE CASCADE,
  user_id INTEGER REFERENCES portal_users(id) ON DELETE SET NULL,
  anonymous_id TEXT,
  stars INTEGER NOT NULL CHECK (stars >= 1 AND stars <= 5),
  status TEXT NOT NULL DEFAULT 'visible' CHECK (status IN ('visible', 'hidden')),
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);
CREATE INDEX IF NOT EXISTS idx_story_ratings_story
  ON story_ratings(story_id, created_at DESC);
CREATE INDEX IF NOT EXISTS idx_story_ratings_status
  ON story_ratings(status);

CREATE TABLE IF NOT EXISTS story_comments (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  story_id INTEGER NOT NULL REFERENCES story_library(id) ON DELETE CASCADE,
  user_id INTEGER REFERENCES portal_users(id) ON DELETE SET NULL,
  anonymous_id TEXT,
  display_name TEXT,
  comment_text TEXT NOT NULL,
  status TEXT NOT NULL DEFAULT 'visible' CHECK (status IN ('visible', 'hidden', 'flagged')),
  flagged_reason TEXT,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);
CREATE INDEX IF NOT EXISTS idx_story_comments_story
  ON story_comments(story_id, created_at DESC);
CREATE INDEX IF NOT EXISTS idx_story_comments_status
  ON story_comments(status);
