-- Migration 0038: Training participant feedback
-- Stores per-participant or per-session feedback and effectiveness ratings.

CREATE TABLE IF NOT EXISTS portal_training_feedback (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  portal_record_id INTEGER NOT NULL REFERENCES portal_records(id) ON DELETE CASCADE,
  participant_id INTEGER REFERENCES portal_training_attendance(id) ON DELETE SET NULL,
  effectiveness_rating INTEGER CHECK(effectiveness_rating BETWEEN 1 AND 5),
  feedback_text TEXT,
  follow_up_recommendations TEXT,
  created_by_user_id INTEGER REFERENCES portal_users(id),
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_training_feedback_record
  ON portal_training_feedback(portal_record_id);
CREATE INDEX IF NOT EXISTS idx_training_feedback_participant
  ON portal_training_feedback(participant_id);
