CREATE TABLE IF NOT EXISTS finance_operation_budgets (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  title TEXT NOT NULL,
  period TEXT NOT NULL,
  owner_id INTEGER REFERENCES portal_users(id),
  status TEXT NOT NULL CHECK(status IN ('draft', 'submitted', 'under_review', 'approved', 'rejected', 'returned', 'closed')) DEFAULT 'draft',
  requested_amount DOUBLE PRECISION NOT NULL DEFAULT 0,
  approved_amount DOUBLE PRECISION NOT NULL DEFAULT 0,
  spent_amount DOUBLE PRECISION NOT NULL DEFAULT 0,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);
CREATE INDEX IF NOT EXISTS idx_finance_operation_budgets_owner ON finance_operation_budgets(owner_id);
CREATE INDEX IF NOT EXISTS idx_finance_operation_budgets_status ON finance_operation_budgets(status);

CREATE TABLE IF NOT EXISTS finance_operation_budget_items (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  budget_id INTEGER NOT NULL REFERENCES finance_operation_budgets(id) ON DELETE CASCADE,
  category TEXT NOT NULL,
  description TEXT NOT NULL,
  quantity DOUBLE PRECISION,
  unit_cost DOUBLE PRECISION,
  total_cost DOUBLE PRECISION NOT NULL,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);
CREATE INDEX IF NOT EXISTS idx_finance_op_budget_items_budget ON finance_operation_budget_items(budget_id);

CREATE TABLE IF NOT EXISTS finance_fund_requests (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  budget_id INTEGER NOT NULL REFERENCES finance_operation_budgets(id) ON DELETE CASCADE,
  requester_id INTEGER NOT NULL REFERENCES portal_users(id),
  requested_amount DOUBLE PRECISION NOT NULL,
  approved_amount DOUBLE PRECISION,
  status TEXT NOT NULL CHECK(status IN ('submitted', 'approved', 'rejected')) DEFAULT 'submitted',
  review_notes TEXT,
  reviewed_by INTEGER REFERENCES portal_users(id),
  submitted_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  reviewed_at TIMESTAMPTZ
);
CREATE INDEX IF NOT EXISTS idx_finance_fund_requests_budget ON finance_fund_requests(budget_id);

ALTER TABLE finance_transactions_ledger ADD COLUMN IF NOT EXISTS budget_id INTEGER REFERENCES finance_operation_budgets(id) ON DELETE SET NULL;
