-- Teacher Phonics & Reading Lesson Observation System
-- Supports full Section A–E form structure from Ozeki RB Foundation observation instrument.

CREATE TABLE IF NOT EXISTS teacher_lesson_observations (
  id                              INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  observation_code                TEXT UNIQUE NOT NULL,

  -- Section A: Administrative Details
  teacher_name                    TEXT NOT NULL,
  observation_date                DATE NOT NULL,
  school_name                     TEXT NOT NULL,
  observer_name                   TEXT NOT NULL,
  class_level                     TEXT NOT NULL,
  lesson_duration                 TEXT NOT NULL,
  learners_present                INTEGER,
  lesson_focus                    TEXT NOT NULL,

  -- Section E4: Overall Post-Observation Rating
  -- 'fidelity' | 'partial' | 'low'
  overall_post_observation_rating TEXT CHECK (overall_post_observation_rating IN ('fidelity','partial','low')),

  -- Signatures
  coach_signature_name            TEXT,
  coach_signature_date            DATE,
  headteacher_dos_signature_name  TEXT,
  headteacher_dos_signature_date  DATE,
  teacher_signature_name          TEXT,
  teacher_signature_date          DATE,

  -- Relational references (nullable for schools not yet in directory)
  school_id                       INTEGER REFERENCES schools_directory(id) ON DELETE SET NULL,
  observer_user_id                INTEGER REFERENCES portal_users(id) ON DELETE SET NULL,
  created_by_user_id              INTEGER NOT NULL REFERENCES portal_users(id),
  updated_by_user_id              INTEGER REFERENCES portal_users(id),

  -- Workflow
  status                          TEXT NOT NULL DEFAULT 'draft'
                                    CHECK (status IN ('draft','submitted','archived')),
  public_visibility               BOOLEAN NOT NULL DEFAULT FALSE,

  created_at                      TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at                      TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_tlo_school_id    ON teacher_lesson_observations(school_id);
CREATE INDEX IF NOT EXISTS idx_tlo_created_by   ON teacher_lesson_observations(created_by_user_id);
CREATE INDEX IF NOT EXISTS idx_tlo_observer     ON teacher_lesson_observations(observer_user_id);
CREATE INDEX IF NOT EXISTS idx_tlo_date         ON teacher_lesson_observations(observation_date DESC);
CREATE INDEX IF NOT EXISTS idx_tlo_status       ON teacher_lesson_observations(status);

-- Section B: Overall Lesson Structure (5 rows)
CREATE TABLE IF NOT EXISTS observation_lesson_structure_items (
  id               INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  observation_id   INTEGER NOT NULL REFERENCES teacher_lesson_observations(id) ON DELETE CASCADE,
  item_key         TEXT NOT NULL,
  item_label       TEXT NOT NULL,
  observed_yes_no  TEXT CHECK (observed_yes_no IN ('yes','no')),
  notes            TEXT,
  UNIQUE (observation_id, item_key)
);
CREATE INDEX IF NOT EXISTS idx_olsi_obs ON observation_lesson_structure_items(observation_id);

-- Sections C & D: Scored rubric criteria (13 items)
CREATE TABLE IF NOT EXISTS observation_scored_items (
  id               INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  observation_id   INTEGER NOT NULL REFERENCES teacher_lesson_observations(id) ON DELETE CASCADE,
  section_key      TEXT NOT NULL,  -- 'c1_gpc' | 'c2_blending' | 'd_engagement'
  section_label    TEXT NOT NULL,
  criteria_key     TEXT NOT NULL,
  criteria_label   TEXT NOT NULL,
  score            INTEGER CHECK (score >= 1 AND score <= 4),
  notes            TEXT,
  UNIQUE (observation_id, criteria_key)
);
CREATE INDEX IF NOT EXISTS idx_osi_obs ON observation_scored_items(observation_id);

-- Section E1: Strengths Observed (up to 4 lines)
CREATE TABLE IF NOT EXISTS observation_strengths (
  id               INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  observation_id   INTEGER NOT NULL REFERENCES teacher_lesson_observations(id) ON DELETE CASCADE,
  line_number      INTEGER NOT NULL CHECK (line_number BETWEEN 1 AND 4),
  content          TEXT NOT NULL DEFAULT '',
  UNIQUE (observation_id, line_number)
);

-- Section E2: Areas for Development (up to 4 lines)
CREATE TABLE IF NOT EXISTS observation_development_areas (
  id               INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  observation_id   INTEGER NOT NULL REFERENCES teacher_lesson_observations(id) ON DELETE CASCADE,
  line_number      INTEGER NOT NULL CHECK (line_number BETWEEN 1 AND 4),
  content          TEXT NOT NULL DEFAULT '',
  UNIQUE (observation_id, line_number)
);

-- Section E3: Agreed Action Plan for Next Visit
CREATE TABLE IF NOT EXISTS observation_action_plans (
  id               INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  observation_id   INTEGER NOT NULL REFERENCES teacher_lesson_observations(id) ON DELETE CASCADE,
  action_to_take   TEXT NOT NULL DEFAULT '',
  resources_needed TEXT NOT NULL DEFAULT '',
  review_date      DATE
);
CREATE INDEX IF NOT EXISTS idx_oap_obs ON observation_action_plans(observation_id);
