-- Chapter markers on session recordings (jump-to-timestamp navigation)
CREATE TABLE IF NOT EXISTS online_training_session_chapters (
  id             INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  session_id     INTEGER NOT NULL REFERENCES online_training_sessions(id) ON DELETE CASCADE,
  title          TEXT    NOT NULL,
  description    TEXT,
  start_seconds  INTEGER NOT NULL CHECK (start_seconds >= 0),
  sort_order     INTEGER NOT NULL DEFAULT 0,
  created_by_user_id INTEGER REFERENCES portal_users(id) ON DELETE SET NULL,
  created_at     TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at     TIMESTAMPTZ NOT NULL DEFAULT NOW()
);
CREATE INDEX IF NOT EXISTS idx_session_chapters_session ON online_training_session_chapters (session_id, sort_order);

-- Discussion threads per session (post-session teacher learning exchange)
CREATE TABLE IF NOT EXISTS online_training_session_discussions (
  id             INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  session_id     INTEGER NOT NULL REFERENCES online_training_sessions(id) ON DELETE CASCADE,
  parent_id      INTEGER REFERENCES online_training_session_discussions(id) ON DELETE CASCADE,
  author_user_id INTEGER NOT NULL REFERENCES portal_users(id) ON DELETE CASCADE,
  author_name    TEXT    NOT NULL,
  body           TEXT    NOT NULL,
  pinned         BOOLEAN NOT NULL DEFAULT FALSE,
  edited_at      TIMESTAMPTZ,
  deleted_at     TIMESTAMPTZ,
  created_at     TIMESTAMPTZ NOT NULL DEFAULT NOW()
);
CREATE INDEX IF NOT EXISTS idx_session_discussions_session ON online_training_session_discussions (session_id, created_at DESC) WHERE deleted_at IS NULL;
CREATE INDEX IF NOT EXISTS idx_session_discussions_parent ON online_training_session_discussions (parent_id) WHERE deleted_at IS NULL;

-- Training programmes (cohort-style courses sequencing multiple sessions)
CREATE TABLE IF NOT EXISTS online_training_programmes (
  id             INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  code           TEXT    UNIQUE,
  title          TEXT    NOT NULL,
  description    TEXT,
  audience       TEXT,
  duration_weeks INTEGER,
  start_date     DATE,
  end_date       DATE,
  status         TEXT    NOT NULL DEFAULT 'draft' CHECK (status IN ('draft','active','completed','archived')),
  cover_image_url TEXT,
  created_by_user_id INTEGER REFERENCES portal_users(id) ON DELETE SET NULL,
  created_at     TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at     TIMESTAMPTZ NOT NULL DEFAULT NOW()
);
CREATE INDEX IF NOT EXISTS idx_programmes_status ON online_training_programmes (status, start_date);

-- Link sessions to a programme in a sequenced order
CREATE TABLE IF NOT EXISTS online_training_programme_sessions (
  id             INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  programme_id   INTEGER NOT NULL REFERENCES online_training_programmes(id) ON DELETE CASCADE,
  session_id     INTEGER NOT NULL REFERENCES online_training_sessions(id) ON DELETE CASCADE,
  sort_order     INTEGER NOT NULL DEFAULT 0,
  required       BOOLEAN NOT NULL DEFAULT TRUE,
  created_at     TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  UNIQUE (programme_id, session_id)
);
CREATE INDEX IF NOT EXISTS idx_programme_sessions_prog ON online_training_programme_sessions (programme_id, sort_order);
CREATE INDEX IF NOT EXISTS idx_programme_sessions_sess ON online_training_programme_sessions (session_id);

-- Teacher enrollment in a programme + auto-computed completion
CREATE TABLE IF NOT EXISTS online_training_programme_enrollments (
  id             INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  programme_id   INTEGER NOT NULL REFERENCES online_training_programmes(id) ON DELETE CASCADE,
  teacher_user_id INTEGER REFERENCES portal_users(id) ON DELETE CASCADE,
  teacher_name   TEXT    NOT NULL,
  teacher_email  TEXT,
  school_id      INTEGER REFERENCES schools_directory(id) ON DELETE SET NULL,
  enrollment_status TEXT NOT NULL DEFAULT 'active' CHECK (enrollment_status IN ('active','completed','dropped')),
  sessions_attended INTEGER NOT NULL DEFAULT 0,
  sessions_required INTEGER NOT NULL DEFAULT 0,
  completed_at   TIMESTAMPTZ,
  created_at     TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at     TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  UNIQUE (programme_id, teacher_user_id),
  UNIQUE (programme_id, teacher_email)
);
CREATE INDEX IF NOT EXISTS idx_programme_enrollments_prog ON online_training_programme_enrollments (programme_id, enrollment_status);
CREATE INDEX IF NOT EXISTS idx_programme_enrollments_teacher ON online_training_programme_enrollments (teacher_user_id);

COMMENT ON TABLE online_training_session_chapters IS 'Chapter markers for session replay (e.g. introduction, demo, practice, Q&A).';
COMMENT ON TABLE online_training_session_discussions IS 'Post-session discussion threads where teachers share classroom adaptations.';
COMMENT ON TABLE online_training_programmes IS 'Cohort-style courses that sequence multiple sessions (e.g. 8-Week Phonics Mastery).';
COMMENT ON TABLE online_training_programme_enrollments IS 'Teacher enrollment + completion tracking for programme cohorts.';
