-- Assessment cycle windows: term-based scheduling for baseline/progress/endline
CREATE TABLE IF NOT EXISTS assessment_schedule_windows (
  id              INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  assessment_type TEXT    NOT NULL CHECK (assessment_type IN ('baseline','progress','endline')),
  academic_year   INTEGER NOT NULL,
  term_number     INTEGER NOT NULL CHECK (term_number IN (1,2,3)),
  window_open     DATE    NOT NULL,
  window_close    DATE    NOT NULL,
  scope_type      TEXT    NOT NULL DEFAULT 'country' CHECK (scope_type IN ('country','region','subregion','district')),
  scope_id        TEXT,
  notes           TEXT,
  created_by_user_id INTEGER REFERENCES portal_users(id) ON DELETE SET NULL,
  created_at      TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at      TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  CHECK (window_close >= window_open)
);
CREATE INDEX IF NOT EXISTS idx_assessment_windows_year_term ON assessment_schedule_windows (academic_year, term_number);
CREATE INDEX IF NOT EXISTS idx_assessment_windows_type ON assessment_schedule_windows (assessment_type, window_open DESC);

COMMENT ON TABLE assessment_schedule_windows IS 'Term windows when baseline/progress/endline assessments must be submitted; used to drive compliance tracking and reminders.';
