-- Public read-only API keys for Ministry, UNICEF, university partners, etc.
CREATE TABLE IF NOT EXISTS api_keys (
  id              INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  key_prefix      TEXT    NOT NULL UNIQUE,      -- First 12 chars, shown in UI; used for lookup
  key_hash        TEXT    NOT NULL,             -- sha256 hex digest of full key
  name            TEXT    NOT NULL,             -- e.g. "Ministry of Education — Data Team"
  organisation    TEXT,                         -- Partner organisation
  contact_email   TEXT,
  scopes          TEXT[]  NOT NULL DEFAULT ARRAY['read:public']::text[],
  rate_limit_per_minute INTEGER NOT NULL DEFAULT 60,
  rate_limit_per_day    INTEGER NOT NULL DEFAULT 5000,
  status          TEXT    NOT NULL DEFAULT 'active' CHECK (status IN ('active','revoked','expired')),
  last_used_at    TIMESTAMPTZ,
  expires_at      TIMESTAMPTZ,
  created_by_user_id INTEGER REFERENCES portal_users(id) ON DELETE SET NULL,
  created_at      TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  revoked_at      TIMESTAMPTZ,
  revoke_reason   TEXT
);
CREATE INDEX IF NOT EXISTS idx_api_keys_prefix ON api_keys (key_prefix) WHERE status = 'active';
CREATE INDEX IF NOT EXISTS idx_api_keys_status ON api_keys (status, created_at DESC);

-- Usage log for observability + enforcement
CREATE TABLE IF NOT EXISTS api_key_usage_logs (
  id              BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  api_key_id      INTEGER NOT NULL REFERENCES api_keys(id) ON DELETE CASCADE,
  endpoint        TEXT    NOT NULL,
  method          TEXT    NOT NULL,
  status_code     INTEGER NOT NULL,
  latency_ms      INTEGER,
  ip_address      TEXT,
  user_agent      TEXT,
  occurred_at     TIMESTAMPTZ NOT NULL DEFAULT NOW()
);
CREATE INDEX IF NOT EXISTS idx_api_usage_key_time ON api_key_usage_logs (api_key_id, occurred_at DESC);
CREATE INDEX IF NOT EXISTS idx_api_usage_occurred ON api_key_usage_logs (occurred_at DESC);

COMMENT ON TABLE api_keys IS 'Authenticated read-only API keys for external data partners (Ministry, UNICEF, university researchers).';
COMMENT ON TABLE api_key_usage_logs IS 'Per-request audit log; powers rate limiting and usage reports.';
