-- ============================================================================
-- 0054 — Performance Hot-Path Indexes + Runtime Settings Tables
-- ============================================================================
-- Addresses audit findings:
--   * Missing composite indexes causing sequential scans on hot dashboards
--   * Hardcoded USD↔UGX rate + sponsorship tiers leaking into code
-- ============================================================================

-- ---- HOT-PATH COMPOSITE INDEXES -------------------------------------------

-- school-intelligence.ts: repeated (school_id, assessment_type) scans for
-- baseline/endline composites
CREATE INDEX IF NOT EXISTS idx_assessment_records_school_type
  ON assessment_records (school_id, assessment_type);

-- learner-profile + cycle timelines ordered by date
CREATE INDEX IF NOT EXISTS idx_assessment_records_learner_date
  ON assessment_records (learner_uid, assessment_date ASC)
  WHERE learner_uid IS NOT NULL;

-- national-intelligence.ts: benchmarks grouped by class_grade + assessment_type
CREATE INDEX IF NOT EXISTS idx_assessment_records_grade_type
  ON assessment_records (class_grade, assessment_type)
  WHERE class_grade IS NOT NULL;

-- class roster latest-per-learner: partial index on recent rows
CREATE INDEX IF NOT EXISTS idx_assessment_records_school_grade
  ON assessment_records (school_id, class_grade);

-- teacher observation joins (school_intelligence + training-effectiveness)
CREATE INDEX IF NOT EXISTS idx_tlo_school_status_date
  ON teacher_lesson_observations (school_id, status, observation_date DESC);

-- training attendance composite for coverage/distinct-teacher queries
CREATE INDEX IF NOT EXISTS idx_pta_school_teacher_attended
  ON portal_training_attendance (school_id, teacher_uid)
  WHERE attended IS TRUE AND teacher_uid IS NOT NULL;

-- item diagnostics: item_key grouping across all responses
CREATE INDEX IF NOT EXISTS idx_assessment_item_responses_item_key
  ON assessment_item_responses (item_key);

-- ---- RUNTIME SETTINGS ------------------------------------------------------

-- Single-row key/value store for ops-configurable settings (support email,
-- phone, KPI fallbacks, etc.). Typed via data_type column.
CREATE TABLE IF NOT EXISTS system_settings (
  id            INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  setting_key   TEXT    NOT NULL UNIQUE,
  setting_value TEXT    NOT NULL,
  data_type     TEXT    NOT NULL DEFAULT 'string' CHECK (data_type IN ('string','int','float','json','bool')),
  description   TEXT,
  updated_by_user_id INTEGER REFERENCES portal_users(id) ON DELETE SET NULL,
  created_at    TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at    TIMESTAMPTZ NOT NULL DEFAULT NOW()
);
CREATE INDEX IF NOT EXISTS idx_system_settings_key ON system_settings (setting_key);

-- Currency conversion rates (replaces hardcoded `3750` and `3800` scattered
-- across public-impact.ts, finance-intelligence.ts, calculator page, etc.)
CREATE TABLE IF NOT EXISTS currency_rates (
  id            INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  from_currency TEXT    NOT NULL,
  to_currency   TEXT    NOT NULL,
  rate          NUMERIC(14, 6) NOT NULL,
  source        TEXT,
  is_active     BOOLEAN NOT NULL DEFAULT TRUE,
  effective_at  TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  created_at    TIMESTAMPTZ NOT NULL DEFAULT NOW()
);
CREATE UNIQUE INDEX IF NOT EXISTS idx_currency_rates_active_pair
  ON currency_rates (from_currency, to_currency)
  WHERE is_active IS TRUE;

-- Sponsorship pricing tiers (replaces hardcoded $250/$15,000/$75,000 blocks)
CREATE TABLE IF NOT EXISTS sponsorship_tiers (
  id            INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  tier_key      TEXT    NOT NULL UNIQUE,
  title         TEXT    NOT NULL,
  subtitle      TEXT,
  amount_usd    NUMERIC(10, 2) NOT NULL,
  amount_ugx    NUMERIC(12, 0),
  description   TEXT,
  features_json TEXT    NOT NULL DEFAULT '[]',
  highlight     BOOLEAN NOT NULL DEFAULT FALSE,
  sort_order    INTEGER NOT NULL DEFAULT 0,
  is_active     BOOLEAN NOT NULL DEFAULT TRUE,
  created_at    TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at    TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

-- ---- SEED DEFAULT DATA ----------------------------------------------------

INSERT INTO currency_rates (from_currency, to_currency, rate, source, is_active)
VALUES ('UGX', 'USD', 0.000267, 'seed-default', TRUE)
ON CONFLICT DO NOTHING;

-- Note: sponsorship_tiers seed reflects the previously-hardcoded values.
-- Admins can adjust via a future settings UI without a deploy.
INSERT INTO sponsorship_tiers (tier_key, title, subtitle, amount_usd, description, features_json, highlight, sort_order, is_active)
VALUES
  ('school', 'Sponsor a School', '2-Year Full Literacy Support Package',
   250, 'Equip a single school with complete structured phonics mastery packs, teacher coaching, and baseline assessments.',
   '["100+ decodable readers","Expert teacher training (2 days)","Direct school impact report"]',
   FALSE, 1, TRUE),
  ('district', 'Sponsor a District', 'District-wide literacy acceleration',
   15000, 'Scale literacy interventions across a focused district. Support an entire cluster of schools synchronously.',
   '["Reach up to 60 Schools","Mass Teacher capacity building","Quarterly District-level KPIs","VIP Partner Dashboard access"]',
   TRUE, 2, TRUE),
  ('region', 'Sub-Region Partner', 'Systemic transformation',
   75000, 'Macro-level implementation driving systemic change across entire Uganda regional demographics.',
   '["Policy & Ministry Alignment","Comprehensive Telemetry Data","Dedicated Ozeki Program Manager"]',
   FALSE, 3, TRUE)
ON CONFLICT (tier_key) DO NOTHING;

COMMENT ON TABLE system_settings IS 'Ops-configurable runtime settings (support contacts, USD/UGX fallbacks, etc.); typed via data_type.';
COMMENT ON TABLE currency_rates IS 'Exchange rates; exactly one is_active row per (from, to) pair.';
COMMENT ON TABLE sponsorship_tiers IS 'Publicly-listed sponsorship packages; replaces hardcoded arrays in sponsor page.';
