-- Idempotency keys for payment initiation endpoints.
-- Stores one row per (key, scope) with the serialized response body; retries
-- with the same key return the original response instead of creating duplicate
-- donation/sponsorship/service records.
CREATE TABLE IF NOT EXISTS idempotency_keys (
  id              INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  idempotency_key TEXT    NOT NULL,
  scope           TEXT    NOT NULL,
  request_hash    TEXT    NOT NULL,
  response_body   TEXT    NOT NULL,
  response_status INTEGER NOT NULL,
  created_at      TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  expires_at      TIMESTAMPTZ NOT NULL,
  UNIQUE (idempotency_key, scope)
);
CREATE INDEX IF NOT EXISTS idx_idempotency_expires ON idempotency_keys (expires_at);

COMMENT ON TABLE idempotency_keys IS 'Stores cached responses for deduplicated write operations. Clients send Idempotency-Key header; duplicate requests with the same (key, scope) return the cached response.';
