-- ============================================================================
-- 0058 — Finance approvals, segregation of duties, period locks, audit chain
-- ============================================================================
-- Institutional-grade controls:
--   * approval_thresholds: configurable amount bands -> required approver roles
--   * finance_approvals:   signed approval events per expense (one row per role)
--   * finance_period_locks: once closed, no retroactive edits
--   * finance_audit_chain: hash-chained log of every finance state change
-- All tables additive; existing finance_expenses/receipts untouched.
-- ============================================================================

-- Thresholds: above each amount (UGX), the listed role chain must approve in order.
CREATE TABLE IF NOT EXISTS finance_approval_thresholds (
  id              INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  min_amount_ugx  NUMERIC(14, 2) NOT NULL,
  required_roles  TEXT[] NOT NULL,
  description     TEXT,
  is_active       BOOLEAN NOT NULL DEFAULT TRUE,
  created_at      TIMESTAMPTZ NOT NULL DEFAULT NOW()
);
CREATE INDEX IF NOT EXISTS idx_approval_thresholds_amount
  ON finance_approval_thresholds (min_amount_ugx DESC)
  WHERE is_active IS TRUE;

-- Seed default 3-tier policy. Admins can adjust via the settings UI.
INSERT INTO finance_approval_thresholds (min_amount_ugx, required_roles, description)
VALUES
  (0,         ARRAY['programme_lead']::text[],                         'Routine spend — single programme-lead approval.'),
  (500000,    ARRAY['programme_lead','finance_manager']::text[],       'Mid-sized spend — programme lead + finance manager.'),
  (5000000,   ARRAY['programme_lead','finance_manager','executive_director']::text[], 'Material spend — full approval chain.')
ON CONFLICT DO NOTHING;

-- Per-expense per-role approval event. Multi-row = multi-tier chain.
CREATE TABLE IF NOT EXISTS finance_approvals (
  id                    INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  expense_id            INTEGER NOT NULL REFERENCES finance_expenses(id) ON DELETE CASCADE,
  required_role         TEXT    NOT NULL,
  approver_user_id      INTEGER REFERENCES portal_users(id) ON DELETE SET NULL,
  decision              TEXT    NOT NULL DEFAULT 'pending'
                          CHECK (decision IN ('pending','approved','rejected','skipped')),
  decision_at           TIMESTAMPTZ,
  decision_notes        TEXT,
  -- Cryptographic binding: hash of (expense_id, required_role, approver, decision, timestamp)
  -- so approval events are tamper-evident even if DB is later mutated.
  signature_hash        TEXT,
  sequence_number       INTEGER NOT NULL,
  created_at            TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  UNIQUE (expense_id, required_role)
);
CREATE INDEX IF NOT EXISTS idx_finance_approvals_pending
  ON finance_approvals (required_role, created_at)
  WHERE decision = 'pending';
CREATE INDEX IF NOT EXISTS idx_finance_approvals_expense
  ON finance_approvals (expense_id, sequence_number);

COMMENT ON TABLE finance_approvals IS 'Multi-tier approval chain per expense. Segregation of duties: approver_user_id must not equal expense.created_by_user_id (enforced at API level).';

-- Period locks: once closed, no DML on finance_expenses / finance_receipts whose
-- date falls in the locked period. Enforced via trigger.
CREATE TABLE IF NOT EXISTS finance_period_locks (
  id                INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  period_start      DATE    NOT NULL,
  period_end        DATE    NOT NULL,
  locked_at         TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  locked_by_user_id INTEGER REFERENCES portal_users(id) ON DELETE SET NULL,
  reason            TEXT,
  CHECK (period_end >= period_start),
  UNIQUE (period_start, period_end)
);
CREATE INDEX IF NOT EXISTS idx_finance_period_locks_range
  ON finance_period_locks (period_start, period_end);

COMMENT ON TABLE finance_period_locks IS 'Once FY/quarter is closed, rows in this table block retroactive edits to finance_expenses and finance_receipts in that date range.';

-- Trigger function: block UPDATE/DELETE on locked-period expenses.
CREATE OR REPLACE FUNCTION check_finance_period_lock()
RETURNS TRIGGER AS $$
DECLARE
  target_date DATE;
  lock_count  INTEGER;
BEGIN
  target_date := COALESCE((TG_OP = 'DELETE' AND OLD.date IS NOT NULL) :: boolean AND OLD.date, NEW.date);
  IF TG_OP = 'DELETE' THEN
    target_date := OLD.date;
  ELSE
    target_date := NEW.date;
  END IF;
  IF target_date IS NULL THEN
    RETURN COALESCE(NEW, OLD);
  END IF;

  SELECT COUNT(*) INTO lock_count FROM finance_period_locks
    WHERE target_date BETWEEN period_start AND period_end;
  IF lock_count > 0 THEN
    RAISE EXCEPTION 'Finance period containing % is locked. Post a reversing journal entry instead of editing the original row.', target_date
      USING ERRCODE = '23514'; -- check_violation
  END IF;
  RETURN COALESCE(NEW, OLD);
END;
$$ LANGUAGE plpgsql;

DROP TRIGGER IF EXISTS trg_finance_expenses_period_lock ON finance_expenses;
CREATE TRIGGER trg_finance_expenses_period_lock
  BEFORE UPDATE OR DELETE ON finance_expenses
  FOR EACH ROW EXECUTE FUNCTION check_finance_period_lock();

-- For receipts, the lock date column is receipt_date.
CREATE OR REPLACE FUNCTION check_finance_receipt_period_lock()
RETURNS TRIGGER AS $$
DECLARE
  target_date DATE;
  lock_count  INTEGER;
BEGIN
  IF TG_OP = 'DELETE' THEN
    target_date := OLD.receipt_date;
  ELSE
    target_date := NEW.receipt_date;
  END IF;
  IF target_date IS NULL THEN
    RETURN COALESCE(NEW, OLD);
  END IF;

  SELECT COUNT(*) INTO lock_count FROM finance_period_locks
    WHERE target_date BETWEEN period_start AND period_end;
  IF lock_count > 0 THEN
    RAISE EXCEPTION 'Finance period containing % is locked. Post a reversing entry instead of editing this receipt.', target_date
      USING ERRCODE = '23514';
  END IF;
  RETURN COALESCE(NEW, OLD);
END;
$$ LANGUAGE plpgsql;

DROP TRIGGER IF EXISTS trg_finance_receipts_period_lock ON finance_receipts;
CREATE TRIGGER trg_finance_receipts_period_lock
  BEFORE UPDATE OR DELETE ON finance_receipts
  FOR EACH ROW EXECUTE FUNCTION check_finance_receipt_period_lock();

-- ============================================================================
-- Tamper-evident audit chain
-- ============================================================================
-- Every finance state change appends one row. Each row's `chain_hash` = SHA256
-- of prior row's chain_hash + this row's canonical payload. Any retroactive
-- edit to an earlier row breaks the chain and is visible on verify.
CREATE TABLE IF NOT EXISTS finance_audit_chain (
  id                 BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  sequence_number    BIGINT NOT NULL UNIQUE,
  event_type         TEXT   NOT NULL,      -- expense.created, expense.approved, period.locked, etc.
  target_table       TEXT   NOT NULL,
  target_id          TEXT   NOT NULL,
  actor_user_id      INTEGER REFERENCES portal_users(id) ON DELETE SET NULL,
  payload_json       TEXT   NOT NULL,
  prev_hash          TEXT   NOT NULL,      -- empty string for the first row
  chain_hash         TEXT   NOT NULL,
  occurred_at        TIMESTAMPTZ NOT NULL DEFAULT NOW()
);
CREATE INDEX IF NOT EXISTS idx_audit_chain_target
  ON finance_audit_chain (target_table, target_id, occurred_at DESC);
CREATE INDEX IF NOT EXISTS idx_audit_chain_event
  ON finance_audit_chain (event_type, occurred_at DESC);

-- Daily verification checkpoints (appended by cron; auditors trust these).
CREATE TABLE IF NOT EXISTS finance_audit_checkpoints (
  id                INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  checkpoint_date   DATE   NOT NULL UNIQUE,
  last_sequence     BIGINT NOT NULL,
  last_chain_hash   TEXT   NOT NULL,
  verified_ok       BOOLEAN NOT NULL,
  rows_verified     BIGINT NOT NULL,
  broken_at         BIGINT,        -- if verified_ok = FALSE, the first broken sequence
  created_at        TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

-- ============================================================================
-- Mandatory source documents above threshold
-- ============================================================================
-- Configured in the settings UI; read at post-time. Above this amount, an
-- expense cannot transition from 'submitted' to 'posted' without at least one
-- uploaded receipt file.
INSERT INTO system_settings (setting_key, setting_value, data_type, description)
VALUES ('finance.mandatory_attachment_threshold_ugx', '100000', 'int',
        'Expenses above this UGX amount require at least one uploaded source document before posting.')
ON CONFLICT (setting_key) DO NOTHING;

COMMENT ON TABLE finance_audit_chain IS 'Append-only, hash-chained log of every finance state change. Daily cron verifies the chain + writes a checkpoint consumable by external auditors.';
