-- Reconciliation link table.
--
-- finance_statement_lines (0003) shipped with match_status/matched_amount but
-- never had a place to record WHICH ledger transaction a line was reconciled
-- against, and no matches table existed — so the reconciliation match/unmatch
-- flow could not be implemented. This adds that link.
--
-- One statement line may be reconciled against multiple ledger transactions
-- (a split), so this is a child table rather than a column on the line. The
-- line's roll-up (matched_amount + match_status) is recomputed from the sum of
-- its matches. UNIQUE(statement_line_id, ledger_txn_id) prevents linking the
-- same pair twice. Idempotent (IF NOT EXISTS) for the bootstrap-every-deploy
-- model.
CREATE TABLE IF NOT EXISTS finance_statement_matches (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  statement_line_id INTEGER NOT NULL REFERENCES finance_statement_lines(id) ON DELETE CASCADE,
  ledger_txn_id INTEGER NOT NULL REFERENCES finance_transactions_ledger(id) ON DELETE CASCADE,
  matched_amount DOUBLE PRECISION NOT NULL DEFAULT 0,
  created_by_user_id INTEGER NOT NULL REFERENCES portal_users(id),
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  UNIQUE (statement_line_id, ledger_txn_id)
);
CREATE INDEX IF NOT EXISTS idx_fin_stmt_match_line ON finance_statement_matches(statement_line_id);
CREATE INDEX IF NOT EXISTS idx_fin_stmt_match_ledger ON finance_statement_matches(ledger_txn_id);
