# Generated by Django 4.2.29 on 2026-03-12 10:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Expense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('legacy_id', models.IntegerField(blank=True, null=True, unique=True)),
                ('expense_number', models.CharField(max_length=64, unique=True)),
                ('vendor_name', models.CharField(max_length=255)),
                ('date', models.DateField()),
                ('category', models.CharField(default='Expense', max_length=120)),
                ('subcategory', models.CharField(blank=True, max_length=120)),
                ('amount', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('currency', models.CharField(choices=[('UGX', 'UGX'), ('USD', 'USD')], default='UGX', max_length=8)),
                ('payment_method', models.CharField(max_length=32)),
                ('description', models.TextField()),
                ('notes', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('submitted', 'Submitted'), ('posted', 'Posted'), ('void', 'Void')], default='draft', max_length=24)),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('posted_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='FinanceContact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('legacy_id', models.IntegerField(blank=True, null=True, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('emails', models.JSONField(blank=True, default=list)),
                ('phone', models.CharField(blank=True, max_length=40)),
                ('whatsapp', models.CharField(blank=True, max_length=40)),
                ('address', models.TextField(blank=True)),
                ('contact_type', models.CharField(choices=[('donor', 'Donor'), ('partner', 'Partner'), ('sponsor', 'Sponsor'), ('other', 'Other')], default='other', max_length=24)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('legacy_id', models.IntegerField(blank=True, null=True, unique=True)),
                ('invoice_number', models.CharField(max_length=64, unique=True)),
                ('category', models.CharField(max_length=120)),
                ('issue_date', models.DateField()),
                ('due_date', models.DateField()),
                ('currency', models.CharField(choices=[('UGX', 'UGX'), ('USD', 'USD')], default='UGX', max_length=8)),
                ('notes', models.TextField(blank=True)),
                ('subtotal', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('total', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('balance_due', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('sent', 'Sent'), ('partial', 'Partial'), ('paid', 'Paid'), ('void', 'Void')], default='draft', max_length=24)),
                ('contact', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='invoices', to='finance.financecontact')),
            ],
            options={
                'ordering': ['-issue_date', '-id'],
            },
        ),
        migrations.CreateModel(
            name='PublicFinanceSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('legacy_id', models.IntegerField(blank=True, null=True, unique=True)),
                ('month', models.CharField(max_length=16)),
                ('currency', models.CharField(choices=[('UGX', 'UGX'), ('USD', 'USD')], default='UGX', max_length=8)),
                ('summary_json', models.JSONField(blank=True, default=dict)),
                ('status', models.CharField(choices=[('private_uploaded', 'Private Uploaded'), ('published', 'Published'), ('archived', 'Archived')], default='private_uploaded', max_length=24)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Receipt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('legacy_id', models.IntegerField(blank=True, null=True, unique=True)),
                ('receipt_number', models.CharField(max_length=64, unique=True)),
                ('category', models.CharField(max_length=120)),
                ('received_from', models.CharField(max_length=255)),
                ('receipt_date', models.DateField()),
                ('amount_received', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('currency', models.CharField(choices=[('UGX', 'UGX'), ('USD', 'USD')], default='UGX', max_length=8)),
                ('payment_method', models.CharField(max_length=32)),
                ('description', models.TextField(blank=True)),
                ('notes', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('issued', 'Issued'), ('void', 'Void')], default='draft', max_length=24)),
                ('issued_at', models.DateTimeField(blank=True, null=True)),
                ('contact', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='receipts', to='finance.financecontact')),
                ('related_invoice', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='receipts', to='finance.invoice')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='MonthlyStatement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('month', models.CharField(max_length=16)),
                ('currency', models.CharField(choices=[('UGX', 'UGX'), ('USD', 'USD')], default='UGX', max_length=8)),
                ('period_type', models.CharField(default='monthly', max_length=24)),
                ('total_money_in', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('total_money_out', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('net', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('breakdown_by_category', models.JSONField(blank=True, default=dict)),
            ],
            options={
                'ordering': ['-month', '-id'],
                'unique_together': {('month', 'currency', 'period_type')},
            },
        ),
        migrations.CreateModel(
            name='LedgerTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('txn_type', models.CharField(choices=[('money_in', 'Money In'), ('money_out', 'Money Out')], max_length=24)),
                ('source_type', models.CharField(choices=[('receipt', 'Receipt'), ('expense', 'Expense'), ('invoice', 'Invoice'), ('manual', 'Manual')], max_length=24)),
                ('source_id', models.BigIntegerField(blank=True, null=True)),
                ('date', models.DateField()),
                ('category', models.CharField(max_length=120)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=14)),
                ('currency', models.CharField(choices=[('UGX', 'UGX'), ('USD', 'USD')], default='UGX', max_length=8)),
                ('posted_status', models.CharField(choices=[('posted', 'Posted'), ('void', 'Void')], default='posted', max_length=16)),
                ('notes', models.TextField(blank=True)),
            ],
            options={
                'ordering': ['-date', '-id'],
                'indexes': [models.Index(fields=['source_type', 'source_id'], name='finance_led_source__0ef7d4_idx'), models.Index(fields=['txn_type', 'date'], name='finance_led_txn_typ_dff96c_idx')],
            },
        ),
        migrations.CreateModel(
            name='InvoiceItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('description', models.CharField(max_length=255)),
                ('qty', models.DecimalField(decimal_places=2, default=1, max_digits=10)),
                ('unit_price', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('line_total', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='finance.invoice')),
            ],
            options={
                'ordering': ['invoice_id', 'id'],
            },
        ),
        migrations.CreateModel(
            name='FinanceAuditException',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('entity_type', models.CharField(max_length=32)),
                ('entity_id', models.BigIntegerField()),
                ('severity', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High')], max_length=16)),
                ('rule_code', models.CharField(max_length=64)),
                ('message', models.TextField()),
                ('status', models.CharField(choices=[('open', 'Open'), ('acknowledged', 'Acknowledged'), ('resolved', 'Resolved'), ('overridden', 'Overridden')], default='open', max_length=24)),
                ('amount', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('currency', models.CharField(choices=[('UGX', 'UGX'), ('USD', 'USD')], default='UGX', max_length=8)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('resolved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='finance_exceptions_resolved', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
