# Generated by Django 4.2.29 on 2026-03-12 10:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('schools', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Learner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('legacy_id', models.IntegerField(blank=True, null=True, unique=True)),
                ('uid', models.CharField(max_length=64, unique=True)),
                ('full_name', models.CharField(max_length=255)),
                ('class_grade', models.CharField(max_length=32)),
                ('age', models.PositiveIntegerField()),
                ('gender', models.CharField(choices=[('boy', 'Boy'), ('girl', 'Girl'), ('other', 'Other')], max_length=16)),
                ('internal_child_id', models.CharField(blank=True, max_length=64)),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='learners', to='schools.school')),
            ],
            options={
                'ordering': ['school_id', 'class_grade', 'full_name'],
            },
        ),
    ]
