# Generated by Django 4.2.29 on 2026-03-12 10:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('schools', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SchoolVisit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('legacy_id', models.IntegerField(blank=True, null=True, unique=True)),
                ('uid', models.CharField(blank=True, default='', max_length=64)),
                ('visit_date', models.DateField()),
                ('visit_type', models.CharField(choices=[('observation', 'Observation'), ('coaching', 'Coaching'), ('follow_up', 'Follow-up')], max_length=24)),
                ('visit_reason', models.CharField(blank=True, max_length=120)),
                ('implementation_status', models.CharField(choices=[('started', 'Started'), ('partial', 'Partial'), ('strong', 'Strong')], default='started', max_length=24)),
                ('focus_areas', models.JSONField(blank=True, default=list)),
                ('leadership_notes', models.TextField(blank=True)),
                ('demo_notes', models.TextField(blank=True)),
                ('coach', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='visits', to='schools.school')),
            ],
            options={
                'ordering': ['-visit_date', 'id'],
            },
        ),
        migrations.CreateModel(
            name='VisitParticipant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('role_at_time', models.CharField(blank=True, max_length=120)),
                ('attended', models.BooleanField(default=True)),
                ('contact', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='schools.schoolcontact')),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='schools.school')),
                ('visit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participants', to='visits.schoolvisit')),
            ],
            options={
                'ordering': ['visit_id', 'contact_id'],
                'unique_together': {('visit', 'contact')},
            },
        ),
    ]
