# Generated by Django 4.2.29 on 2026-03-12 10:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('schools', '0001_initial'),
        ('learners', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AssessmentSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('legacy_id', models.IntegerField(blank=True, null=True, unique=True)),
                ('uid', models.CharField(max_length=64, unique=True)),
                ('assessment_date', models.DateField()),
                ('assessment_type', models.CharField(choices=[('baseline', 'Baseline'), ('progress', 'Progress'), ('endline', 'Endline')], max_length=16)),
                ('class_grade', models.CharField(max_length=32)),
                ('tool_version', models.CharField(default='EGRA-v1', max_length=32)),
                ('model_version', models.CharField(blank=True, max_length=64)),
                ('benchmark_version', models.CharField(blank=True, max_length=64)),
                ('scoring_profile_version', models.CharField(blank=True, max_length=64)),
                ('assessor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assessment_sessions', to='schools.school')),
            ],
            options={
                'ordering': ['-assessment_date', 'id'],
            },
        ),
        migrations.CreateModel(
            name='AssessmentResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('legacy_id', models.IntegerField(blank=True, null=True, unique=True)),
                ('source_row_key', models.CharField(blank=True, max_length=64)),
                ('letter_identification_score', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('sound_identification_score', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('decodable_words_score', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('story_reading_score', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('reading_comprehension_score', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('computed_reading_level', models.CharField(blank=True, max_length=64)),
                ('computed_level_band', models.IntegerField(blank=True, null=True)),
                ('fluency_accuracy_score', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('learner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assessment_results', to='learners.learner')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='results', to='assessments.assessmentsession')),
            ],
            options={
                'ordering': ['session_id', 'id'],
            },
        ),
    ]
