# Generated by Django 4.2.29 on 2026-03-12 10:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('schools', '0001_initial'),
        ('visits', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LessonEvaluation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('legacy_id', models.IntegerField(blank=True, null=True, unique=True)),
                ('lesson_date', models.DateField()),
                ('grade', models.CharField(blank=True, max_length=32)),
                ('lesson_focus', models.JSONField(blank=True, default=list)),
                ('strengths_text', models.TextField(blank=True)),
                ('priority_gap_text', models.TextField(blank=True)),
                ('next_coaching_action', models.TextField(blank=True)),
                ('teacher_commitment', models.TextField(blank=True)),
                ('overall_score', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('status', models.CharField(choices=[('active', 'Active'), ('void', 'Void')], default='active', max_length=16)),
                ('evaluator', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lesson_evaluations', to='schools.school')),
                ('teacher', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lesson_evaluations', to='schools.teacher')),
                ('visit', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lesson_evaluations', to='visits.schoolvisit')),
            ],
            options={
                'ordering': ['-lesson_date', 'id'],
            },
        ),
        migrations.CreateModel(
            name='LessonEvaluationItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('domain_key', models.CharField(max_length=64)),
                ('item_key', models.CharField(max_length=64)),
                ('score', models.PositiveSmallIntegerField()),
                ('note', models.TextField(blank=True)),
                ('evaluation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='evaluations.lessonevaluation')),
            ],
            options={
                'ordering': ['evaluation_id', 'domain_key', 'item_key'],
                'unique_together': {('evaluation', 'item_key')},
            },
        ),
    ]
