# Generated by Django 4.2.29 on 2026-03-12 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ImpactReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('legacy_id', models.IntegerField(blank=True, null=True, unique=True)),
                ('report_code', models.CharField(max_length=64, unique=True)),
                ('title', models.CharField(max_length=255)),
                ('scope_type', models.CharField(choices=[('country', 'Country'), ('region', 'Region'), ('subregion', 'Subregion'), ('district', 'District'), ('school', 'School')], max_length=16)),
                ('scope_value', models.CharField(max_length=255)),
                ('period_start', models.DateField(blank=True, null=True)),
                ('period_end', models.DateField(blank=True, null=True)),
                ('narrative_json', models.JSONField(blank=True, default=dict)),
                ('fact_pack_json', models.JSONField(blank=True, default=dict)),
                ('is_public', models.BooleanField(default=False)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-published_at', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PublicDashboardAggregate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('scope_type', models.CharField(choices=[('country', 'Country'), ('region', 'Region'), ('subregion', 'Subregion'), ('district', 'District'), ('school', 'School')], max_length=16)),
                ('scope_value', models.CharField(max_length=255)),
                ('period_key', models.CharField(default='FY', max_length=32)),
                ('kpis', models.JSONField(blank=True, default=dict)),
                ('domain_breakdown', models.JSONField(blank=True, default=dict)),
                ('teaching_quality', models.JSONField(blank=True, default=dict)),
                ('data_quality', models.JSONField(blank=True, default=dict)),
            ],
            options={
                'ordering': ['scope_type', 'scope_value', '-updated_at'],
                'unique_together': {('scope_type', 'scope_value', 'period_key')},
            },
        ),
    ]
